### ISSUE TITLE
CTDB EAC Plugin v.2.1.8

### ISSUE THREAD

**Issue by Barough** [gchudov/cuetools.net#100]
Updated the old CTDB Plugin that EAC v1.6 ships with to the new v2.1.8 a couple of days ago. I've ripped 4 albums after that with EAC but there is no trace of any CTDB logging in the EAC logs (yes, the plugin is enabled in EAC). I've also run these 4 rips through CUETools v2.1.8 'HF1' and these 4 albums is in the CTDB according to CT's 'Verify'.

-

korth at HA have verified this issue.

https://hydrogenaud.io/index.php?topic=120871.0

**Comment by c72578** [comment]
Thanks for your report.
In the meantime I could do some investigations.
Please copy the file **`Newtonsoft.Json.dll`** also to e.g. `c:\Program Files (x86)\Exact Audio Copy\` or where EAC is installed.
I will add this file to `CUETools.CTDB.EACPlugin.2.1.8.zip` and the `interop\EAC\` directory for future versions.

**Comment by Barough** [comment]
I'll give that a try and report back after my next rip.

**Comment by c72578** [comment]
**`CUETools.CTDB.EACPlugin.2.1.8.zip`** has been updated and includes **`Newtonsoft.Json.dll`** now. It can be downloaded from here:
https://github.com/gchudov/cuetools.net/releases/download/v2.1.8/CUETools.CTDB.EACPlugin.2.1.8.zip

**Comment by Barough** [comment]
That seems to have solved it. :)

**Comment by c72578** [comment]
Thanks for checking.

**Comment by Barough** [comment]
> 
> 
> Thanks for checking.

Making another rip now to verify

**Comment by ha-korth** [comment]
Working.

**Comment by Barough** [comment]
3 rips now and it's working fine now.
