### ISSUE TITLE
Excessive art download

### ISSUE THREAD

**Issue by rrroscar** [gchudov/cuetools.net#104]
In 2.18 HF1 it is impossible NOT to download all pictures from musicbrainz/coverartarchive.org for each disc of a set, which is annoying and takes time. There should be an option to just tag without any artwork.

**Comment by ha-korth** [comment]
![CR218](https://user-images.githubusercontent.com/36651918/116769558-11819800-aa0b-11eb-85a6-0cc4ef3fa117.jpg)
