### ISSUE TITLE
[CUETools 2.1.8, 2.1.9] Cannot create new profile

### ISSUE THREAD

**Issue by ha-korth** [gchudov/cuetools.net#113]
https://hydrogenaud.io/index.php?topic=121380
When trying to create a new profile, parts of the settings file created are missing, making the profile unusable. This worked properly in 2.1.7.

![profile](https://user-images.githubusercontent.com/36651918/128377252-e411bf6a-cfcc-4cb4-9ec0-5725775682c8.jpg)

The resulting **profile-new.txt** settings file is missing all encoders, all decoders, and all CustomFormats.

> [...]
> AlArtFilenameFormat=folder.jpg
> Advanced={
> =  "encoders": [],
> =  "decoders": []
> =}
> CustomFormats=0
> CustomScript0Name=default
> [...]

This change appears to be introduced somewhere between
[2bde923](https://github.com/gchudov/cuetools.net/commit/2bde92380a2ed7cf46e67609b345e2be9d211639) and [73a5c05](https://github.com/gchudov/cuetools.net/commit/73a5c05dc26390eb7800c25cb39025e44be3d57a)

**Comment by RDamman** [comment]
Behaviour confirmed. The problem is the copy constructor of CUEConfigAdvanced called from line 219 in CUEConfig.cs. Here are the encoders, decoders and customformats copied from the existing profile.

**Comment by c72578** [comment]
A test build with the suggested fix by @RDamman  has been prepared in PR #122, please check.

**Comment by ha-korth** [comment]
Created a working profile on first use of test build.
