### ISSUE TITLE
Opus icon not displayed in CUERipper

### ISSUE THREAD

**Issue by acc987** [gchudov/cuetools.net#114]
This is surely a minor issue, but I noticed that the Opus icon for the lossy encoder is displayed in CUETools

![OpusIconDisplayedInCUETools](https://user-images.githubusercontent.com/39603492/129324536-611d89d3-bc1f-4e21-9846-98f4c6fe3447.png)

but not in CUERipper:

![OpusIconMissingInCUERipper](https://user-images.githubusercontent.com/39603492/129324552-417377e5-0516-4827-9720-fbf6bb015802.png)

(Software version is 2.1.9 as you can see from the screenshots.)

**Comment by c72578** [comment]
@acc987 thanks for your report and the screenshots, which show the details. The missing icon will be added.
