### ISSUE TITLE
Change of CD not detected in CUERipper

### ISSUE THREAD

**Issue by RDamman** [gchudov/cuetools.net#115]
If I change the CD in my Samsung SH-S203B SB04 drive, the meta data is not updated with the meta data / tracklist of the new CD. Even pressing the Reload button does not change CD information (CUETools 2.1.7 on Windows 10). Pressing F5 does change the CD meta data  / tracklist to the new CD.

**Comment by RDamman** [comment]
It seems the problem is possible caused by that I have multiple DVD drives in my system. When the first drive is used in CUERipper, the problem seems not to occur.

**Comment by ha-korth** [comment]
I had a similar issue (same drive, only drive on system) with 2.1.6, but that system isn't currently active. The current CUERipper version is 2.1.9. Does the issue persist in the newer version?

**Comment by RDamman** [comment]
> 
> 
> I had a similar issue (same drive, only drive on system) with 2.1.6, but that system isn't currently active. The current CUERipper version is 2.1.9. Does the issue persist in the newer version?

Tested with 2.1.9 and the problem still exists there.

**Comment by RDamman** [comment]
I have made another test. In CDRipper drive B is selected. If I change the CD in drive B the meta data / tracklist is not updated to reflect the new CD. Now if I change the CD in drive A, the meta data/tracklist in CDRipper (set on drive B) is updated to the new CD in drive B.

**Comment by RDamman** [comment]
It seems like the problem can be mitigated by adding 1 line of code in frmCUERipper.cs (line 1764):
        private void buttonEjectDisk_Click(object sender, EventArgs e)
        {
            if (selectedDriveInfo != null)
                selectedDriveInfo.drive.EjectDisk();
            **UpdateDrive();**
        }

The problem seems to be caused by an optimization/bug in Windows. The problem also appears in the Explorer of Windows. Click in the Explorer in the left pane on "This Computer" so that it shows all the drivers on the right. Put another application (i.e. CUERipper) on the foreground with the drives in the explorer still visible. Eject the problematic cd drive (in my case drive B as mentioned above) by pressing the Eject button on the drive. As you will see, ejecting the CD is not visible in the Explorer as it is not visible in CUERipper. This is because the Windows message WM_DEVICECHANGE / DBT_DEVICEREMOVECOMPLETE is not send. Click in the explorer on the problematic drive (which is still showing it has a CD loaded) and the data refreshes in the Explorer but also CUERipper receives a late WM_DEVICECHANGE / DBT_DEVICEREMOVECOMPLETE message. So by accessing (opening) the drive, the data is refreshed. This is also the case if you call UpdateDrive() after ejecting the CD with the eject button in CUERipper.
Loading a CD is not problematic after a **DBT_DEVICEREMOVECOMPLETE** message is received in CUERipper. With the insertion of a CD the expected WM_DEVICECHANGE / **DBT_DEVICEARRIVAL** is received in CUERipper and the Tracklist / Meta Data is updated.
