### ISSUE TITLE
support international characters in titles within .m3u

### ISSUE THREAD

**Issue by isidroco** [gchudov/cuetools.net#118]
When within a .m3u there are titles like "Sueños" or "Música" CueTools gives error.  With .CUE there's no problem

**Comment by ha-korth** [comment]
Does it work with these titles when the m3u file is encoded UTF-8 or UTF-8 BOM ? (with m3u extension, not m3u8)

An m3u file is supposed to be non-Unicode but CUETools doesn't support m3u8.

**Comment by isidroco** [comment]
Just standard ANSI, same as CUE sheet.  If a song name contains ANSI chars >128 on a .M3U file it fails to process it.  Just rename a song filename adding one of these: á é í ó ú ñ  and try to use CueTools on it.  .CUEs are correctly processed, and .M3U fails.

**Comment by c72578** [comment]
@isidroco Thanks for your report.
As a workaround, you can convert your .M3U file in `ANSI` format to `UTF-8` or `UTF-8-BOM`.
This can be done e.g. using [Notepad++](https://notepad-plus-plus.org/downloads/)
- Open foo.m3u in Notepad++
- Encoding - Convert to UTF-8
- File - Save As... - "foo_utf8.m3u"

Or, if you prefer from command line (Powershell 6.2 or newer):
```PowerShell
Get-Content -Encoding 1252 .\foo.m3u | Set-Content -Encoding utf8 foo_utf8.m3u
```

**Comment by c72578** [comment]
@isidroco Could you please test the following build with your `ANSI` `.M3U` files:
https://github.com/gchudov/cuetools.net/pull/138#issuecomment-956217990
