### ISSUE TITLE
[2.1.7] Unhandled Exception

### ISSUE THREAD

**Issue by ha-korth** [gchudov/cuetools.net#12]
> Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'CUETools.ALACEnc.exe' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.
File name: 'CUETools.ALACEnc.exe'

Windows 10 Pro v1803 
.net 3.5, 4.7.2

removing
`<startup><supportedRuntime version="v2.0.50727"/></startup>`
from CUETools.ALACEnc.exe.config eliminates message and runs normally.

**Comment by c72578** [comment]
Thanks for reporting.
Looks like `<supportedRuntime version="v4.0"/>` is required here.
This needs to be fixed in cuetools.net/CUETools.ALACEnc/App.config
