### ISSUE TITLE
metadata tags not written if disc only has one track (CD-Singles)

### ISSUE THREAD

**Issue by w4hnsinn** [gchudov/cuetools.net#121]
My CUETools 2.1.6. is set up to write the above mentioned metadata tags (that is to say, AR and CTDB confidence) when using the "Verify" profile.

This works as expected for all albums, EPs, compilations, etc. etc. that have multiple tracks on the CD.

**It fails** however if the CD only has one track (CD-Singles). The verification runs fine, the accurip file is written to disk, but the metadata tags are not added to the files. I have made sure this is not an access error, write permission issue, or naming problem, and I have seen this happen with two different CD-Singles now.

**Comment by ha-korth** [comment]
Confirmed in current version 2.1.9
The following not written on single track
_Verify mode_
Write AccurateRip tags (Verify)
Write CTDB tags on verify
Write CDTOC tag 
_Encode mode_
Write AccurateRip tags (Encode and verify)
Write CTDB tags on encode
Write CDTOC tag

**Comment by RDamman** [comment]
What happens if you rip the track in CUERipper not in **tracks** mode but in **image** mode (combobox left bottom)?

![afbeelding](https://user-images.githubusercontent.com/4113866/132338831-493a3edb-b5c4-4509-9df5-8d499e9b7eb2.png)

**Comment by c72578** [comment]
@ha-korth Thanks for confirming the issue.
Are the tags written now on single track in your case using the test build ([CUETools_2.1.9_2021-10-26_git_3505229.zip](https://github.com/gchudov/cuetools.net/files/7418403/CUETools_2.1.9_2021-10-26_git_3505229.zip))?
