### ISSUE TITLE
Problem with moving converted folders too different path 

### ISSUE THREAD

**Issue by cluber77** [gchudov/cuetools.net#130]
I just encoded some of my albums via cuetools as one single file with embedded cue.
After I finish to encoding the file I moved the converted files with their folder to external hard drive and then I make a New verification of the  Converted files and now it’s not checking the folder.
I’m getting this error: could not find a part of the path....
If I’m moving the folders back to the original converted folder I’m getting the option to verify the albums.
I hope that you can fix this problem.

**Comment by c72578** [comment]
The described problem could not be reproduced with the provided description. Feel free to reopen, if there is still an issue.
