### ISSUE TITLE
"Exception: Block size too large" when ripping Zac Brown Band The Comeback

### ISSUE THREAD

**Issue by SiloReed** [gchudov/cuetools.net#139]
When I ripped the new Zac Brown Band CD, The Comeback. CUERipper.exe version 2.1.9.0 displays "Exception: Block size too large" even though all tracks seem to be ripped. The cover art image that is download is 3000x3000 perhaps that has something to do with the exception.

**Comment by c72578** [comment]
@SiloReed Thanks for your report.
This behavior is intentional:
`Prevent taglib from corrupting flac files when embedded album art exceeds 16Mb`
https://github.com/gchudov/taglib-sharp/commit/8590ad068dade84e9bc15656a451221b852f11d7

**Comment by c72578** [comment]
BTW, the original cover art of the mentioned album has got more than 20 MB:
https://coverartarchive.org/release/7e079a0a-d95e-44fa-b5cf-f44ae2132e8f/30671803484.jpg

Smaller sizes of the cover are available:
https://musicbrainz.org/release/7e079a0a-d95e-44fa-b5cf-f44ae2132e8f/cover-art

In CUERipper Options you can switch "Album art size" from "Large" to "Small".
