### ISSUE TITLE
M4A tags truncated in 2.1.8 & 2.1.9

### ISSUE THREAD

**Issue by rgoubet** [gchudov/cuetools.net#142]
When I encode files with Cuetools 2.1.8 or 2.1.9 to M4A using QAAC, tags with long names are truncated, e.g.

MUSICBRAINZ_ALBUMARTISTID -> CBRAINZ_ALBUMARTISTID

I even get tags named L or C.

**Comment by c72578** [comment]
@rgoubet Thanks for your report.
The issue could be reproduced (tested with qaac v2.72 from https://github.com/nu774/qaac).
It has appeared in CUETools 2.1.7. Currently you can use CUETools 2.1.6 to circumvent these tagging issues using qaac.
The following tags are affected:

Tag | Truncated Tag
--- | ---
CTDBDISCCONFIDENCE | DISCCONFIDENCE
CTDBTRACKCONFIDENCE | TRACKCONFIDENCE
CDTOC | C
RELEASECOUNTRY | ASECOUNTRY
Publisher | ISHER
LABELNO | LNO
MusicBrainz Album Release Date | cBrainz Album Release Date
MusicBrainz Album Release Country | cBrainz Album Release Country
LABEL | L
CATALOGNUMBER | LOGNUMBER

**Comment by c72578** [comment]
@rgoubet Could you please test this build of CUETools with updated taglib-sharp, which includes m4a fixes:
https://github.com/gchudov/cuetools.net/pull/147#issuecomment-985784082
