### ISSUE TITLE
Exception when selecting more complex "best match"

### ISSUE THREAD

**Issue by Ottileinchen** [gchudov/cuetools.net#148]
CUETool 2.1.9 on Win 10: I get an "Exception: Object reference not set to an instance of an object" dialog when I "GO", and then select one of the three more complicated entries. Only "Unknown Artist - Unknown Title" works.
![Clipboard01](https://user-images.githubusercontent.com/37915741/144763844-705acbc3-10b6-43bc-ad10-4d9fbea38642.jpg)

**Comment by DuMichAuch72** [comment]
Windows has limitations on the length of path and file names. Maybe this is causing the exception

**Comment by Ottileinchen** [comment]
The limit would be 260 characters, the longest file path/name would be 145 characters in one of the cases. So: no, that's not the problem. I also tried to replace the ":" (to be seen in titles 6, 7, 8), which also did not help.

**Comment by c72578** [comment]
How many chars has the directory including subdirectories got, where the files are converted too?
e.g. `foo\bar` in:
`C:\foo\bar\Converted\Handel; English Chamber Orchestra, Raymond Leppard\1994 - Music for the Royal Fireworks _ Water Music\Handel; English Chamber Orchestra, Raymond Leppard - Music for the Royal Fireworks _ Water Music.cue`

**Comment by Ottileinchen** [comment]
the complete path to the source *.cue:
Q:\SOUND\CDs\Händel-Feuerwerk, Wasser\Händel_Feuerwerk_Wasser.cue
the complete path to the destination, as resulting from selecting and "Ok"ing "Unknown...":
Q:\SOUND\CDs\Händel-Feuerwerk, Wasser\Re-Encode1\Händel_Feuerwerk_Wasser.cue
![WaterMusicSelection](https://user-images.githubusercontent.com/37915741/144825662-3b8aa252-2963-4f34-afbc-ba1e9d90d099.png)
\Händel-Feuerwerk, Wasser\Re-Encode1\Händel_Feuerwerk_Wasser.cue
an extended screen shot of the selection window, showing all the track titles, is attached.

**Comment by c72578** [comment]
@Ottileinchen In the meantime I could obtain the CD for testing:
![CUETools_01](https://user-images.githubusercontent.com/371551/148833080-ba975468-a2ba-4131-a81c-d5b66ada2f0c.png)

The CD could be ripped using CUERipper without problems and conversion tests in CUETools were OK.
Tested in CUETools 2.1.9 and 2.2.0:
Mode: Tracks
Audio Output: Lossless, flac (cuetools, 5)

Could you please describe the steps in CUETools, until you observe the error?
Mode, Audio Output.
What is the source audio format?

**Comment by c72578** [comment]
@Ottileinchen  Could you please try CUETools 2.2.0 with the affected album?
For the case that the issue is related to the .cue file being UTF-8 encoded (without BOM).
Support for reading UTF-8 encoded cuesheets (without BOM) has been added in CUETools 2.2.0.

**Comment by Ottileinchen** [comment]
Hi @c72578,

seems that answering to notifications does not work, despite being suggested there...

I do the following (now on CUETools 2.2.0):
- navigate to the cue file in the left pane
- adjust the output filename template a bit, and use it (output cog wheel)
- select encode, tracks, lossless, FLAC (Cuetools)
- Go
- select best match in the upper pane
- Ok
now I get the error popup - or not, depending on which match I selected

I assume that the cue file is not guilty. For Alan Parsons one match works, another doesn't, and as far as I can tell (hex editor), they are plain ASCII, single byte diacritic.

Source were the original CDs, ripped with Exact Audio Copy (Händel) as wav, and ImgBurn (Parsons) as bin. I hope - versions unkonwn.

Best, Otto

[Alan Parsons - LiveSpan Disc 1.cue.zip](https://github.com/gchudov/cuetools.net/files/7876690/Alan.Parsons.-.LiveSpan.Disc.1.cue.zip)
[Händel_Feuerwerk_Wasser.cue.zip](https://github.com/gchudov/cuetools.net/files/7876691/Handel_Feuerwerk_Wasser.cue.zip)
![Alan Parsons](https://user-images.githubusercontent.com/37915741/149655144-3d4ebe96-fdc0-4f3d-bafa-5d10c5275074.png)
![Alan Parsons Match working](https://user-images.githubusercontent.com/37915741/149655148-287f0b35-a94f-4706-b433-9720d14f48ce.png)
![Alan Parsons Match -NOT- working](https://user-images.githubusercontent.com/37915741/149655152-669217e7-05fd-453b-9f89-80703489dcc0.png)

**Comment by c72578** [comment]
@Ottileinchen thanks for providing the details.
I could reproduce the exception now with unticked `Verify using CTDB`.
However, if `Verify using CTDB` is ticked, it works OK.
Could you please try with enabled `Verify using CTDB`:

![Verify_using_CTDB](https://user-images.githubusercontent.com/371551/149672233-7a3a7af6-30a1-4f7d-a31a-1aace85a922f.png)

**Comment by Ottileinchen** [comment]
Yep - here too: no error if 'Verify using CTDB' is ticked. With 'Verify using AccurateRip' only, the error still pops up.
