### ISSUE TITLE
Question about default profile usage with CUETools.exe

### ISSUE THREAD

**Issue by Hrxn** [gchudov/cuetools.net#149]
Maybe it's just me, but I've been reading the wiki and feel a bit confused now..

Consider the very common use case (also mentioned in the wiki):
> Convert a single-file album image with CUE sheet to a file-per-track album image

The documentation page for command-line tools mentions
> `Usage: CUETools.exe [/<profile>] <filename>`

and this profile description:
> /convert     starts a conversion
                      default profile settings include; Action: 'Encode' with Script: 'default'

What does that mean? Default profile settings include "Action: 'Encode'"?

What is it going to encode?

**Comment by ha-korth** [comment]
I'd prefer to answer your questions about the wiki in the [forum](https://hydrogenaud.io/index.php?board=74.0).

The profile settings are configured using the GUI then saved to the settings file. The description of the default settings are settings you would see in the main window.

Converting a single-file album image with CUE sheet to multiple files (a file-per-track) requires writing a new set of files. The encoder used is selected in the audio output section of the main window.

**Comment by Hrxn** [comment]
Ah, thanks..
I wonder if I can still find my old Hydrogrenaudio account.. or maybe it's time to make a new one..

You're obviously right about writing a new set of files. I thought it would be simply about splitting the source file, so the mention of "encode" sent me on the wrong path here..

But okay, I mean, if that's what is actually happening...
Lossless-to-lossless transcoding is still correctly called transcoding, I guess, but yeah, that's not how that term is commonly used..

Closing this now.

**Comment by ha-korth** [comment]
> I wonder if I can still find my old Hydrogenaudio account
One exists for Hrxn. You would just need access to your old gmail account for password recovery.

> Lossless-to-lossless transcoding is still correctly called transcoding, I guess, but yeah, that's not how that term is commonly used.
Encode is the term on the GUI so I really didn't want to use a different term to describe it on the wiki.
