### ISSUE TITLE
CUETools.CTDB.EACPlugin coverart issue

### ISSUE THREAD

**Issue by ha-korth** [gchudov/cuetools.net#150]
quote from 
@gchudov 
> The WebArchive site stopped supporting TLS 1.1.
EAC plugin is built for .NET 2.0 and by default doesn't support TLS 1.2.
Somewhere during plugin startup something like this needs to be done:
ServicePointManager.SecurityProtocol = (SecurityProtocolType)Enum.ToObject(typeof(SecurityProtocolType), 3072);

I assume WebArchive = coverartarchive.org.

**Comment by c72578** [comment]
@ha-korth Thanks for this report.
An updated EAC Plugin has been built for testing:
https://github.com/gchudov/cuetools.net/pull/151#issuecomment-1001714586

**Comment by ha-korth** [comment]
Initial test okay (2 cd's tested).

Note: extensive cover search mode is very slow if there are a lot of covers and there is no OK / Cancel buttons until after the search is complete.
So in primary cover search mode it may also be slow with no way to stop the search.

**Comment by salzrat** [comment]
doesn't work for me (see my comment in the pull request)

**Comment by ha-korth** [comment]
Additional cd's tested on two more systems. Plugin still working okay.

I can confirm the plugin is missing when extracting using Windows Explorer without first unblocking. When extracting after Unblock the plugin shows and works.

**Comment by salzrat** [comment]
What do you mean by „unblocking“?
Also, it seems Cover sizes are limited to small and big, but medium is missing in the plug-in options, so I can’t get 600x600 coverart

**Comment by ha-korth** [comment]
http://cue.tools/wiki/CUETools_Download#Known_Issues_When_Unpacking_the_Archive

**Comment by salzrat** [comment]
Ah ok that fixes it. 
Interestingly, Cover-lookup is shown for some CDs, but not for others. And size options is missing the medium option.
My workaround is: after I get the metadata using ctdb, I change the metadata provider to musicbrainz and right-click on the image placeholder to get a new image.

**Comment by c72578** [comment]
> I can confirm the plugin is missing when extracting using Windows Explorer without first unblocking. When extracting after Unblock the plugin shows and works.

In the meantime the analysis [1] of the updated plugin has been completed by Microsoft and it should no longer be blocked:

*We can confirm that the application `cuetools.ctdb.eacplugin.2.1.9_2021-12-27_git_b662333_fix_eac_coverart.zip` (“eadbca3f28750989cdec06b406ca418d76b4b1cee21975a55a72d58398876769”) has since established reputation and attempting to download or run the application should no longer show any warnings.*

[1] https://www.microsoft.com/en-us/wdsi/filesubmission
