### ISSUE TITLE
CUERipper often fails to work with Pioneer BDR-XD07U drive

### ISSUE THREAD

**Issue by cstoitner** [gchudov/cuetools.net#155]
When ripping CDs with a Pioneer BDR-XD07U drive I regularly get this error: "Exception: Error reading CD: IoctlFailed"
This happens in about 1 of 3 runs in burst mode and makes the more secure modes a pain to use. CueRipper is the only application I could find with this problem. EAC for example works just fine.

Even though the error message is different I tried the build from https://github.com/gchudov/cuetools.net/issues/19#issuecomment-578374465 and it completely fixed the problem. So it seems this drive doesn't work correctly with the 294 C2 error reporting mode either. Interestingly EAC claims C2 reporting is not supported by this drive. CueRipper does seem to get some error information though - I can see retries in the UI when ripping bad CDs in burst mode (when the internal "Audio CD error correction" of the drive is disabled).

The drive is reported as "Used drive              : PIONEER  - BD-RW  BDR-XD07U" in the log file. Its running on the latest firmware  version 1.03 if that matters. Read command from the log with the working build: "BEh, 14h, 42h, 16 blocks at a time", and with the failing builds: "BEh, 12h, 42h, 16 blocks at a time".

**Comment by c72578** [comment]
@cstoitner Thanks for your detailed report.
Could you please test the following build with your `PIONEER - BD-RW BDR-XD07U` drive:
https://github.com/gchudov/cuetools.net/pull/153#issuecomment-1005970020

Direct download link:
https://github.com/gchudov/cuetools.net/files/7824819/CUETools_2.1.9_2022-01-06_git_13f0dbf.zip

**Comment by cstoitner** [comment]
The new build works without problems. Thank you!
