### ISSUE TITLE
[REQUEST] Codec Update - Monkeys Audio

### ISSUE THREAD

**Issue by Barough** [gchudov/cuetools.net#158]
Would be great if the MA codec could be updated. It's at v7.x now.

Current Version : 7.50

**Comment by Barough** [comment]
8.20 (July 11, 2022)

**Comment by Barough** [comment]
v8.4x

**Comment by c72578** [comment]
> Would be great if the MA codec could be updated. It's at v7.x now.
> 
> Current Version : 7.50

@Barough Where is this version info coming from?
The currently used version in CUETools is 4.33, see e.g.:
https://github.com/gchudov/MAC_SDK/blob/cc49a962073d241affa3314e038aa5ac8316d3d4/Source/Shared/All.h#L205
```cs
#define MAC_VERSION_STRING                              _T("4.33")
#define MAC_NAME                                        _T("Monkey's Audio 4.33")
```

**Comment by c72578** [comment]
Remark: The currently used version in CUETools is `4.33`
See e.g.:
https://github.com/gchudov/MAC_SDK/blob/cc49a962073d241affa3314e038aa5ac8316d3d4/Source/Shared/All.h#L205
```cs
#define MAC_VERSION_STRING                              _T("4.33")
#define MAC_NAME                                        _T("Monkey's Audio 4.33")
```

**Comment by Barough** [comment]
Maybe you should wait to the last second before a new release of CT to upgrade MA, since the that author of MA is pushing out updates on his codec like a 'maniac'.

**Comment by Barough** [comment]
Currently at v8.9x

**Comment by Barough** [comment]
Will the latest version of MA get added to the upcoming CUETools release or?

**Comment by Barough** [comment]
Monkeys Audio v9.00 released today

**Comment by c72578** [comment]
> Will the latest version of MA get added to the upcoming CUETools release or?

Yes, CUETools 2.2.3 contains Monkey's Audio 9.04.

**Comment by Barough** [comment]
Noticed that when i tested the pre-build yesterday. ;)
