### ISSUE TITLE
Ripper 2.2.0 having trouble with `HL-DT-ST BD-RE BU40N      1.04`

### ISSUE THREAD

**Issue by bleggett** [gchudov/cuetools.net#164]
```
C:\Users\xxx\Downloads\CUETools_2.2.0>CUETools.Ripper.Console.exe -D F:
CUERipper v2.2.0 Copyright (C) 2008-2022 Grigory Chudov
This is free software under the GNU GPLv3+ license; There is NO WARRANTY, to
the extent permitted by law. <http://www.gnu.org/licenses/> for details.
Drive       : F: [HL-DT-ST BD-RE BU40N      1.04]
Read offset : 6
Read cmd    : BEh, 12h, BEh, 16 blocks at a time
Secure mode : 1
Filename    : Haydn; Orchestra of the 18th Century, Frans Brüggen - Symphonies 88 & 89 _ Sinfonia concertante.wav
Disk length : 61:52:00
AccurateRip : ok
MusicBrainz : Haydn; Orchestra of the 18th Century, Frans Brüggen - Symphonies 88 & 89 / Sinfonia concertante
Retry 04    : 01%; 04.03x; 2103 (0.06%) errors; 00:00:59/00:50:04
```

Reads a bit, retries, reads a bit, retries - etc. EAC works fine with the drive.

**Comment by ha-korth** [comment]
You've tried another drive?
It sounds like you're describing normal operation in secure mode. Each section is read twice (read, retry).
http://cue.tools/wiki/CUERipper_Settings#.2818.29_Extraction_method_.7Bslider.7D
```
(18) Extraction method {slider}

Slide to the desired mode.

    Burst mode = Reads section once. If the drive reports C2 errors, then error correction begins and up to 15 more read retries are done. No CTDB submission will be made because some errors may not have been reported via C2 ("insufficient quality").
    Secure mode = Reads section once, then one retry. If results differ or the drive reports C2 errors, then error correction begins and up to 30 more full or partial read retries are done for that section. (See also: (25) Error Correction Progress bar)
    Paranoid mode = Reads section once, then two retries. If results differ or the drive reports C2 errors then error correction begins and up to 61 more full or partial read retries are done for that section. (See also: (25) Error Correction Progress bar)
```

**Comment by bleggett** [comment]
> Have you tried another CD? Have you tried another drive? I see you are getting errors right from the start of the CD but what you describe sounds like normal operation in secure mode. Each section is read twice (read, retry). http://cue.tools/wiki/CUERipper_Settings#.2818.29_Extraction_method_.7Bslider.7D
> 
> ```
> (18) Extraction method {slider}
> 
> Slide to the desired mode.
> 
>     Burst mode = Reads section once. If the drive reports C2 errors, then error correction begins and up to 15 more read retries are done. No CTDB submission will be made because some errors may not have been reported via C2 ("insufficient quality").
>     Secure mode = Reads section once, then one retry. If results differ or the drive reports C2 errors, then error correction begins and up to 30 more full or partial read retries are done for that section. (See also: (25) Error Correction Progress bar)
>     Paranoid mode = Reads section once, then two retries. If results differ or the drive reports C2 errors then error correction begins and up to 61 more full or partial read retries are done for that section. (See also: (25) Error Correction Progress bar)
> ```

Same CD in same drive works fine in Secure mode EAC.

Same CD in different drive works fine in Cuetools Ripper.

**Comment by c72578** [comment]
@bleggett Could you please try the following build:

[CUETools_2.2.0_2022-02-06_git_9bf0cc0_Mode296_first.zip](https://github.com/gchudov/cuetools.net/files/8010865/CUETools_2.2.0_2022-02-06_git_9bf0cc0_Mode296_first.zip)
`SHA256: 66753c785079c2aae11918444d6d101b469e76049fe1f7ab589d7807adfa6edc`

In this build, `C2ErrorMode.Mode296` is tried first in general, which can be useful for testing drives with C2 mode issues.

It contains the following modification of the code, as reported in #19:
```diff
diff --git a/CUETools.Ripper.SCSI/SCSIDrive.cs b/CUETools.Ripper.SCSI/SCSIDrive.cs
index 59aaea1..f436f98 100644
--- a/CUETools.Ripper.SCSI/SCSIDrive.cs
+++ b/CUETools.Ripper.SCSI/SCSIDrive.cs
@@ -811,7 +811,7 @@ namespace CUETools.Ripper.SCSI
 				return true;
 
 			ReadCDCommand[] readmode = { ReadCDCommand.ReadCdBEh, ReadCDCommand.ReadCdD8h };
-			Device.C2ErrorMode[] c2mode = { Device.C2ErrorMode.Mode294, Device.C2ErrorMode.Mode296, Device.C2ErrorMode.None };
+			Device.C2ErrorMode[] c2mode = { Device.C2ErrorMode.Mode296, Device.C2ErrorMode.Mode294, Device.C2ErrorMode.None };
 			// Mode294 does not work for these drives: LG GH24NSD1, ASUS DRW-24D5MT, PIONEER DVR-S21, PIONEER BDR-XD07U. Try Mode296 first
 			if (Path.Contains("GH24NSD1") || Path.Contains("DRW-24D5MT") || Path.Contains("DVR-S21") || Path.Contains("BDR-XD07U"))
 			{

```
The build has been prepared using GitHub Actions from this commit:
https://github.com/c72578/cuetools.net/commit/9bf0cc077a3384e933ab781f1eeb9c07716a270c

**Comment by bleggett** [comment]
Will do

**Comment by bleggett** [comment]
@c72578 Yep - that build seems to work just fine - reads each section twice, as expected, and moves on to the next section - rather than getting stuck rereading the initial section and not moving on.

**Comment by c72578** [comment]
@bleggett Thanks for checking and reporting the details. It looks like C2 error mode needs to be disabled for this drive, like in EAC.
Just to be sure:
How is the BD-RE BU40N connected to the computer? Any USB3 adapter involved?

**Comment by bleggett** [comment]
> @bleggett Thanks for checking and reporting the details. It looks like C2 error mode needs to be disabled for this drive, like in EAC.
> Just to be sure:
> How is the BD-RE BU40N connected to the computer? Any USB3 adapter involved?
> 

It's plugged directly into the back of my PC via USB3.

**Comment by bleggett** [comment]
@c72578 This one: https://www.amazon.com/gp/product/B0193X0KKO/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

**Comment by c72578** [comment]
@bleggett Thanks for sharing the details, so it is a  USB 3.0 Slim SATA Optical Drive Enclosure.
Could you please test the following:
- Plug the drive into a `USB 2.0` port (if available)
- Otherwise use a `USB 2.0` extension cable, which will force USB 2.0 mode.

Possibly related issue: #71

**Comment by bleggett** [comment]
@c72578 I've ordered a USB 2.0 extension cable since I don't have one on hand to test. Will report back. Agree it sounds similar to #71, in that EAC doesn't have an issue with this drive but CueRipper does.

**Comment by bleggett** [comment]
Confirmed - with USB 2.0 cable **and** the test build linked above I get a clean rip from this drive, no errors.

With the USB 2.0 cable and the **regular** 2.2.0 build I get the same behavior I originally described, where the drive gets stuck in a re-read loop of the first section.

With a **USB 3** cable and the test build linked above I get an error at the end of the rip.

EAC continues to work fine with this drive in either USB3 or USB2 configuration.

**Comment by c72578** [comment]
@bleggett That was quick.
Thanks for testing and providing all the details concerning the involved issues.
A fix for the `C2ErrorMode` of the `HL-DT-ST BD-RE BU40N` drive will be implemented.

**Comment by c72578** [comment]
@bleggett could you please check this build, which includes the `C2ErrorMode` fix for `HL-DT-ST BD-RE BU40N` (using the USB 2.0 cable):
https://github.com/gchudov/cuetools.net/pull/168#issuecomment-1036589011

**Comment by bleggett** [comment]
Build works, ripped a CD a few times to check.

Also, I think I have managed to find a "more stable" USB3 port on my motherboard - with the test build and WITHOUT the USB2 extensions (USB3 mode), ripping seems to work fine - so gonna chalk that up to some mismatch between my motherboard and the drive enclosure that somehow EAC doesn't expose, but Cueripper does.

For reference, my motherboard is `ASRock Fatal1ty B450 ITX` and the ports marked USB3.1 Gen 1 in this diagram seem to be stable with this enclosure and Cueripper:

![wgbyj2mfhnk51](https://user-images.githubusercontent.com/854255/153696621-a2016411-d8a5-4bf5-ace5-226c81e1839d.png)

**Comment by c72578** [comment]
Thanks for testing and sharing the details about the USB ports.
