### ISSUE TITLE
Error: Unsupported audio type

### ISSUE THREAD

**Issue by gabriels1963** [gchudov/cuetools.net#177]
I have CUETools set in environment PATH on Windows 11 64-bit
I have run:
CUETools /verify a.flac
CUETools /verify b.flac
.
.
.
CUETools /verify z.flac

No matter which file I tried they all give the same error:
Processing N:\Converted\1-01.flac:
Error: Unsupported audio type: N:\Converted\1-01.flac
----------------------------------------------------------

These files play without any error in foobar200 and VLC.

**Comment by c72578** [comment]
Please have a look at:
https://github.com/gchudov/cuetools.net/issues/87#issuecomment-789240544
It is important that the downloaded zip file and subsequently the plugin files are unblocked.

You can have a look at `CUETools - Advanced Settings - Decoders` and check if the required decoder is blocked.

**Comment by c72578** [comment]
Furthermore there is the possibility, that the plugin dlls are not found, because they are typically in a subdirectory of CUETools and might not be in the environment PATH.

**Comment by gabriels1963** [comment]
dir -Path C:\Tools\CUETools -Recurse | Unblock-File solves the problem for me
Is there an option to get the result from the command line for I can run it in a batch mode on all my files?

**Comment by ha-korth** [comment]
http://cue.tools/wiki/Command-line_Tools
The command-line for CUETools.exe was not intended to be used in a Windows batch. User interaction is required to close a Window after each CD is processed.
