### ISSUE TITLE
WavPack dll flagged as malware

### ISSUE THREAD

**Issue by nokti** [gchudov/cuetools.net#180]
The WavPack dll of CUETools 2.2.1 in \CUETools\plugins\win32 is flagged as malware by Malwarebytes.
See: https://forums.malwarebytes.com/topic/285706-cuetools-221-false-positive/

I'm also wondering if it's the official WavPack dll because it's half the size as the one downloaded from: https://www.wavpack.com/downloads.html

**Comment by c72578** [comment]
Hello,
WavPack is a submodule of cuetools under: https://github.com/gchudov/cuetools.net/tree/master/ThirdParty
The dll is directly compiled from the WavPack source code, which happens during the release process of CUETools using a GitHub Action. For usage in cuetools, the dll is compiled as `MultiThreadedDLL`. Furthermore, `DSD` is disabled. This explains the difference in size compared to https://github.com/dbry/WavPack/releases/download/5.4.0/wavpack-5.4.0-dll.zip
For details, see e.g.: https://github.com/gchudov/WavPack/commit/c2d60b18d7247dc6739e7e2d55947dbb836d3172

Concerning the false positive:
If you report a false positive and get as answer "Please see this." speaks already volumes ...

**Comment by nokti** [comment]
> If you report a false positive and get as answer "Please see this." speaks already volumes ...

Yes, that reply was astonishing, almost as if I was the one to blame. I've been using CUETools and Malwarebytes for years and never had a problem.

**Comment by c72578** [comment]
In the meantime `CUETools_2.2.1\plugins\win32\wavpackdll.dll` is not detected as a false positive anymore by Malwarebytes.
See: https://www.virustotal.com/gui/file/8cf8443ddfb2c9986cc52b748515d1e7e18dacc853a181d21884ef15bd7c3639
