### ISSUE TITLE
CUERipper fails in a very weird way with LG GH24NSD1

### ISSUE THREAD

**Issue by radorn** [gchudov/cuetools.net#19]
Sorry for the crappy title, but this problem I'm having keeps giving me twists and surprises, so I don't even know what to put there. I'm sorry because this is going to be a bit long.

With a certain drive I have, I keep getting this error:
"Exception: Error reading CD: medium error: UNRECOVERED READ ERROR"

I've tried many things and along the way I was surprised with what I found out, so I'll start with the last discovery and then go through some of the strange events that preceeded it.

I'm running Windows 7 64bit, and I have an LG GH24NSD1 SATA drive. It works as far as detecting the disc, reading the TOC, finding drive features, detecting gaps... and then it fails when trying to extract the audio. I thought there was something wrong with the drive itself for a long time, but then yesterday I loaded a Windows XP VM I have under VirtualBox and put this drive in passthrough mode to the VM, and ran CUERipper from there and it worked without a hitch, and very fast.
What's weirder thing is that if I close the VM and immediately open CUERipper from the host OS, I can actually rip one disc. But, after that rip finishes or, if I abort it, attempting a second rip fails with that same error again.

Prior to this, I tried everything I could think of: Disabling HTOA and gap detection, using burst mode, zero offset, running as administrator, and even setting several compatibility modes (XP sp3, sp2, 2000... 98!). Nothing worked.

I have other drives, which are all IDE, connected to an IDE channel built into the motherboard, not an add-in controller card: An LG DVD-RAM multidrive, two Plextor CD-RWs, and even a 52x LG CD-ROM. All of them work right with CUERipper, mostly. I don't know what is the problem, wether the drives themselves, the OS or the ripping software.

But there's even more strangeness going on, because Exact Audio Copy does read from that LG SATA drive without the need for loading that VM first.
That said, I've been having quite a bit of trouble with all drives before. Even if the drive works in EAC under the host OS (win7), sometimes it goes sluggish, or just throws read and sync errors all the time, but other times it doesn't.

As you can see this is a mess. I have had other problems too, but I'm not sure they'd add any relevant information. Maybe everything would be fixed with a fresh OS install. Maybe some update in the last two years or so messed things up. I really have no idea. It's all very weird.

UPDATE: I just emptied an old HDD and tried installing both windows 7 and windows 10 fresh and run CUERipper from there. I keep getting the same error, so I'd say a faulty OS installation is ruled out.

**Comment by SebastianZimmer** [comment]
I can confirm this: I'm having the same issue with my LG GH24NSD1 (on Win 10), so it indeed seems related to the CD drive model.

**Comment by ky7749** [comment]
I just bought an ASUS DRW-24D5MT which is really just an LG GH24NSB0. It shows exactly the same symptom as the bug submitter's LG GH24NSD1.

I accidentally discovered a workaround. Unfortunately it requires modifying the source code and recompile. A sketchy procedure:

1. Set up a local CueTools.NET source according to the instructions in `Readme.md.`
2. Open the solution with Visual Studio 2017.
3. Locate the folder `Ripper`, find a project named `CUETools.Ripper.SCSI`, and a file named `SCSIDrive.cs` within.
4. Open the file and go to line 787 or so.
5. Change the line

`Device.C2ErrorMode[] c2mode = { Device.C2ErrorMode.Mode294, Device.C2ErrorMode.Mode296, Device.C2ErrorMode.None };`

to

`Device.C2ErrorMode[] c2mode = { Device.C2ErrorMode.Mode296, Device.C2ErrorMode.Mode294, Device.C2ErrorMode.None };`

[ In the original code, the C2 error mode '294' was tried first and succeeded, but it caused the symptom later on. By swapping, '296' was tried first and did not cause problem. I was able to complete ripping several discs. But frankly, I have no idea what 294 and 296 mean. ]
 
6. Recompile.

7. Copy the compiled binaries (exe's, dll's, etc) into a 'correct' directory structure. (Download CUETools_2.1.7.zip, unzip it. Try to recreate _that_ directory layout with the compiled binaries).

8. Try running the modified CueRipper. You should no longer get the symptom.

**Comment by ky7749** [comment]
By the way I came across another DVD drive (PLDS DVDROM DA8DESH BL6M) on a Levono ThinkCentre PC. Using CueRipper with this drive gave similar symptom, except that the error message at the end was `Exception: Error reading CD: hardware error: TIMEOUT ON LOGICAL UNIT`. The workaround seemed to work.

**Comment by radorn** [comment]
Good discovery! So, the problem is related to C2 handling, it seems.
¿Could you share those binaries? I'm done ripping discs for a while, but I wouldn't mind having those handy just in case.

**Comment by ky7749** [comment]
Here is a 7z file containing the binaries.

1. Couldn't get the build process to build some plugins. They are missing in the archive.
2. CueRipper.exe with flac output is working.

**Comment by ky7749** [comment]
Here is a 7z file containing the binaries.

1. Couldn't get the build process to build some plugins. They are missing in the archive.
2. CueRipper.exe with flac output is working.
 
[CueTools-2.1.7-workaround.zip](https://github.com/gchudov/cuetools.net/files/4106695/CueTools-2.1.7-workaround.zip)

**Comment by radorn** [comment]
Ya! it verks!
Thank you so much!

**Comment by ky7749** [comment]
Rebuilt against commit 2bde923 with mods, in order to get more complete output:

1. My workaround.

2. Unwanted icon scaling removed in the CueRipper and CueTools interfaces.

    `CUERipper -> frmCUERipper.cs -> statusStrip1 -> ImageScalingSize` reset to default `(16, 16)`.
    `CUERipper -> frmCUERipper.cs -> statusStrip1 -> Size` set to `(664, 25)`.
   
    `CUETools -> frmCUETools.cs -> statusStrip1 -> ImageScalingSize` reset to default `(16, 16)`.
    `CUETools -> frmCUETools.cs -> statusStrip1 -> Size` reset to default `(684, 26)`.
   
    `CUETools -> frmCUETools.cs -> toolStripMenu -> ImageScalingSize` reset to default `(16, 16)`.
   
3. `CUETools.CTDB.EACPlugin` targets .NET 4.7 (set via project property)

4. `CUETools.Codecs.TTA` targets .NET 4.7 (set via project property)

[cuetools-2.1.7-workaround-v2.zip](https://github.com/gchudov/cuetools.net/files/4111608/cuetools-2.1.7-workaround-v2.zip)

**Comment by ky7749** [comment]
Off-topic remark: WMA encoding and decoding do not work; the constructor declarations of WMA encoder and decoder are wrong. CueTools uses Activator.CreateInstance() to create objects, which does not work.

Declaration: `CUETools.Codecs.WMA -> AudioEncoder.cs` and `AudioDecoder.cs`.
Instantation: `CUETools.Processor -> AudioReadWrite.cs`, line 31 and 69 [see `Activator.CreateInstance()` calls].

**Comment by radorn** [comment]
Who wants WMA anyway? :D

**Comment by c72578** [comment]
> 
> 
> Off-topic remark: WMA encoding and decoding do not work; the constructor declarations of WMA encoder and decoder are wrong. CueTools uses Activator.CreateInstance() to create objects, which does not work.
> 
> Declaration: `CUETools.Codecs.WMA -> AudioEncoder.cs` and `AudioDecoder.cs`.
> Instantation: `CUETools.Processor -> AudioReadWrite.cs`, line 31 and 69 [see `Activator.CreateInstance()` calls].

@ky7749 Thanks for investigating and reporting the issue about the constructors in the WMA codec.
Would you be happy to submit a PR, if you already have a fix?
Thanks in advance.

**Comment by c72578** [comment]
@ky7749 I have submitted PR #72 concerning the reported WMA constructor issue. Feel free to have a look.

**Comment by c72578** [comment]
@ky7749 Thanks for investigating this issue and sharing all the details.
@radorn, @ky7749 Feel free to test a current build of CUETools with the affected drives **`LG GH24NSD1`** or **`ASUS DRW-24D5MT`**, which can be downloaded here: #97

**Comment by c72578** [comment]
@ky7749 Could you please post a screenshot of CUERipper, which shows the details, how your `ASUS DRW-24D5MT` drive, including firmware version is detected?
Remark: There has been a different report for an `ASUS DRW-24D5MT` drive with firmware 2.00 : https://github.com/gchudov/cuetools.net/issues/107#issuecomment-864203030
