### ISSUE TITLE
Exception on clicking link

### ISSUE THREAD

**Issue by rabelux** [gchudov/cuetools.net#2]
Exception is raised on clicking the link referring to `cuetools.net` in "about"
![cuetoolsexception](https://user-images.githubusercontent.com/16120882/43679753-27079b6a-982b-11e8-8508-979e45c06bdd.png)
Win 7 64bit

**Comment by c72578** [comment]
Thanks for reporting.
The problem was caused by an incorrect LinkArea in frmAbout.de-DE.resx.
