### ISSUE TITLE
CUERipper have troubles with HP PLDS DVDRW DU8AESH 6HSM: "UNRECOVERED READ ERROR"

### ISSUE THREAD

**Issue by SpFNn00j34g** [gchudov/cuetools.net#205]
Hi, I was trying to rip a CD with the HP PLDS DVDRW DU8AESH 6HSM drive but I get this error at around 90%: "Exception: Error reading CD: medium error: UNRECOVERED READ ERROR". I think it's the same trouble as #19 and #133, is there any solution? Thanks and best regards

**Comment by c72578** [comment]
@SpFNn00j34g Thanks for your report.
Which version of CUETools are you using?
Does this also happen with other CDs or only this one at around 90%?

**Comment by SpFNn00j34g** [comment]
> 

Hi, thanks for your reply.

I'm using the latest version (2.2.2) and unfortunately it's the only music CD I have, so I wouldn't be sure if the problem is only with that disc.

It always happens when it's around 90%, it never gets to complete the process.

Regards!

**Comment by c72578** [comment]
@SpFNn00j34g Thanks for the additional details.

Could you please try the following build from PR #203 according to the instructions below:

[CUETools_2.2.2_2022-07-08_git_0352518_Add_setting_for_C2ErrorMode.zip](https://github.com/gchudov/cuetools.net/files/9072088/CUETools_2.2.2_2022-07-08_git_0352518_Add_setting_for_C2ErrorMode.zip)
`SHA256: 44cd07b69125bb8710a8d80d4a7cb02498dd09e680d5c01ba554e362e13c7486`

- Rename the file:
`user_profiles_enabled -> user_profiles_disabled`
In this case, the settings.txt file will later be in a subdirectory of the unpacked CUETools zip file
- Start `CUERipper` once and close it. Aftwards there will be the file `CUERipper\settings.txt`
- Edit the `settings.txt` file and try the three different C2ErrorModes, to see if one of them works and 100% of the CD can be read.
- CUERipper should be closed before editing and started again after each editing is finished.
- Examples:

Edited `settings.txt` file, C2ErrorMode `0` (None)
```xml
=  <DriveC2ErrorModes>
=    <item>
=      <key>
=        <string>HP PLDS DVDRW DU8AESH 6HSM</string>
=      </key>
=      <value>
=        <int>0</int>
=      </value>
=    </item>
=  </DriveC2ErrorModes>
```

Edited `settings.txt` file, C2ErrorMode `1` (Mode294)
```xml
=  <DriveC2ErrorModes>
=    <item>
=      <key>
=        <string>HP PLDS DVDRW DU8AESH 6HSM</string>
=      </key>
=      <value>
=        <int>1</int>
=      </value>
=    </item>
=  </DriveC2ErrorModes>
```
Edited `settings.txt` file, C2ErrorMode `2` (Mode296)
```xml
=  <DriveC2ErrorModes>
=    <item>
=      <key>
=        <string>HP PLDS DVDRW DU8AESH 6HSM</string>
=      </key>
=      <value>
=        <int>2</int>
=      </value>
=    </item>
=  </DriveC2ErrorModes>
```

Please report back results from these three tests.

**Comment by SpFNn00j34g** [comment]
> @SpFNn00j34g Thanks for the additional details.
> 
> Could you please try the following build from PR #203 according to the instructions below:
> 
> [CUETools_2.2.2_2022-07-08_git_0352518_Add_setting_for_C2ErrorMode.zip](https://github.com/gchudov/cuetools.net/files/9072088/CUETools_2.2.2_2022-07-08_git_0352518_Add_setting_for_C2ErrorMode.zip) `SHA256: 44cd07b69125bb8710a8d80d4a7cb02498dd09e680d5c01ba554e362e13c7486`
> 
> * Rename the file:
>   `user_profiles_enabled -> user_profiles_disabled`
>   In this case, the settings.txt file will later be in a subdirectory of the unpacked CUETools zip file
> * Start `CUERipper.exe` once and close it. Aftwards there will be the file `CUERipper\settings.txt`
> * Edit the `settings.txt` file and try the three different C2ErrorModes, to see if one of them works and 100% of the CD can be read.
> * CUERipper should be closed before editing and started again after each editing is finished.
> * Examples:
> 
> Edited `settings.txt` file, C2ErrorMode `0` (None)
> 
> ```
> =  <DriveC2ErrorModes>
> =    <item>
> =      <key>
> =        <string>HP PLDS DVDRW DU8AESH 6HSM</string>
> =      </key>
> =      <value>
> =        <int>0</int>
> =      </value>
> =    </item>
> =  </DriveC2ErrorModes>
> ```
> 
> Edited `settings.txt` file, C2ErrorMode `1` (Mode294)
> 
> ```
> =  <DriveC2ErrorModes>
> =    <item>
> =      <key>
> =        <string>HP PLDS DVDRW DU8AESH 6HSM</string>
> =      </key>
> =      <value>
> =        <int>1</int>
> =      </value>
> =    </item>
> =  </DriveC2ErrorModes>
> ```
> 
> Edited `settings.txt` file, C2ErrorMode `2` (Mode296)
> 
> ```
> =  <DriveC2ErrorModes>
> =    <item>
> =      <key>
> =        <string>HP PLDS DVDRW DU8AESH 6HSM</string>
> =      </key>
> =      <value>
> =        <int>2</int>
> =      </value>
> =    </item>
> =  </DriveC2ErrorModes>
> ```
> 
> Please report back results from these three tests.

@c72578 
Hello, here it is:
C2ErrorMode `0` (None): Not complete. The process did not complete, but reached up to 96%.
C2ErrorMode `1` (Mode294): Not complete. The process failed to start.
C2ErrorMode `2` (Mode296): Not complete. The process did not complete, but reached up to 95%.

Unfortunately, it still has the same error (they all gave the same "UNRECOVERED READ ERROR" error message) but at least it got over 90%, which I think is progress.

Regards!

**Comment by c72578** [comment]
@SpFNn00j34g Thanks for testing and providing the results.
This confirms, that Mode294 is not working for the DU8AESH drive, which was addressed in https://github.com/gchudov/cuetools.net/commit/8a2398bca6ab693de42e082b5eb0c4946b0d5b7b

How good is the condition of the CD? Are there any visible scratches, fingerprints or cracks? Especially in the outer area, where the read error occurs (90-100%).
Maybe you can do some additional cleaning of the CD, see e.g. [1].

[1] https://www.wikihow.com/Clean-a-Dirty-CD?amp=1

**Comment by c72578** [comment]
@SpFNn00j34g Could you rip the complete CD after cleaning?

**Comment by SpFNn00j34g** [comment]
> 

@c72578 Hi, sorry for the delay.
I just got another CD (unfortunately, not a copy of the same CD) and this one did complete the process properly and successfully. The previous CD seems to have damage, because it has small scratches in certain areas. I didn't notice it the first time.

I am still in the process of looking for a CD cleaner.

Thank you very much for your help and sorry for the inconvenience.

**Comment by c72578** [comment]
@SpFNn00j34g Thanks for sharing the additional information. Good to hear, that a different CD could be ripped completely without any problems.
Can this issue be closed now?
