### ISSUE TITLE
Failed to load FFmpeg.AutoGen

### ISSUE THREAD

**Issue by Daegnor** [gchudov/cuetools.net#207]
I'm trying to extract tracks from a .tta file using a .cue file. I made sure that ffmpeg was installed but I keep having this error: 
`Exception: Can't load file or assembly 'FFmpeg.AutoGen, Version=4.1.0.4, Culture=neutral' or one of its dependencies.`

Can anyone help ?

**Comment by ha-korth** [comment]
I was able to duplicate in v2.2.2 using the default ffmpeg.dll decoder. CUETools throws the error then crashes.
The ttalib decoder seems to work okay
<img width="412" alt="tta" src="https://user-images.githubusercontent.com/36651918/179509239-3d58e82c-81d9-4c2d-a3ce-f8140c9ddbd6.png">
