### ISSUE TITLE
[REQUEST] Codec Update - WavPack v5.5.0

### ISSUE THREAD

**Issue by Barough** [gchudov/cuetools.net#209]
WavPack v5.5.0 is available now

**Comment by c72578** [comment]
WavPack has been updated to 5.5.0 on 9 Jul 2022, see:
https://github.com/gchudov/cuetools.net/pull/204
https://github.com/gchudov/cuetools.net/commit/d0da79efeebc75a7a1e92346e6430189b1a1d1b6

**Comment by Barough** [comment]
totally missed that
