### ISSUE TITLE
screen-reader support/keyboard navigation/keyboard shortcuts

### ISSUE THREAD

**Issue by medlem78** [gchudov/cuetools.net#21]
Most of the cueripper windows and buttons can't be accessed by keyboard. Therefore it is allmost impossible to use the software with screen-reader. To test it, you can download the free screen-reader NVDA.

**Comment by c72578** [comment]
@medlem78 thank you very much for your report. This is a very important point.
- Currently, there is a pull request in preparation (#92), which adds and updates access key shortcuts.
- So far, the tab index has been updated, with the goal to improve navigating using the tab key (18f00da).

Further suggestions from your side to improve accessibility are welcome.

**Comment by c72578** [comment]
@medlem78 Feel free to test a current build from PR #94, where keyboard shortcuts have been added and navigation using the tab key has been updated:
[CUETools_2.1.8_2021-04-03_git_da18f69.zip](https://github.com/gchudov/cuetools.net/files/6252543/CUETools_2.1.8_2021-04-03_git_da18f69.zip)
**`SHA256: 7887d34e77796b8c6f87358f3735b32b15d9452df3bb88dc36a82e6ae677e720`**
