### ISSUE TITLE
How to tagging splitted tracks without re-encoding

### ISSUE THREAD

**Issue by coddoge** [gchudov/cuetools.net#210]
I have splitted m4a(AAC) tracks, but its not tagged.

How to batch tag it without re-encoding?

Like first step of the Action 'Encoding', get metadata from DB and then just write tag in to files, withou re-encoding.

May need to provide more info of the album to search DB, but i can not found the operations in GUI.

**Comment by ha-korth** [comment]
CUETools currently does not have a tool for "tagging only".
You could try [mp3tag](https://www.mp3tag.de/en/) which can tag your m4a(aac) files from sources such as freedb(gnudb.org), musicbrainz, or discogs.

**Comment by coddoge** [comment]
Thank you for reply.

I tried mp3tag, its excellent!
