### ISSUE TITLE
CUETools encoding the same file twice & without showing "Edit Tags" window first

### ISSUE THREAD

**Issue by ffwema** [gchudov/cuetools.net#224]
Steps to reproduce:
- Check a .cue file in "Multiselect Browser" mode and click "Go" button. The "Edit Tags" window appears.
- Click "Close" button on the "Edit Tags" window to dismiss it.
- Click "Go" button again. The program will immediately start encoding without first showing "Edit Tags" window. The encoding will also take place twice resulting in two output files.

**Comment by c72578** [comment]
@ffwema Thanks for reporting this issue and providing the details for reproducing it.

**Comment by ffwema** [comment]
@c72578 Wow, this was fast. Works great now, thank you.
