### ISSUE TITLE
CUERipper - 'Read offset correction' value is NOT added to the 'EAC Style' extraction log

### ISSUE THREAD

**Issue by Barough** [gchudov/cuetools.net#229]
The auto detected 'Read offset correction' value is NOT added to the 'EAC Style' extraction log.  The value in the log is set to '0'.

No issue when you use CUERipper's standard extraction log.

**Comment by c72578** [comment]
@Barough So far, the described issue could not be reproduced.
CUERipper 2.2.2

- Options - Extraction - EAC log style: True (default)
Written to log:
```
Used drive  : TSSTcorp CDDVDW SE-208DB   Adapter: 1  ID: 0
...
Read offset correction                      : 6
```

- Options - Extraction - EAC log style: False
Written to log:
```
...
Used drive              : TSSTcorp - CDDVDW SE-208DB
Read offset correction  : 6
Read command            : BEh, 12h, BEh, 16 blocks at a time
...
```
In both cases the value of the `Read offset correction` is written to the log file.

**Comment by Barough** [comment]
That was weird, Seen it twice myself. Must do some checking again

Was the drive's 'Read offset' auto detected by CUERipper or had you set it manually?

**Comment by c72578** [comment]
> 
> Was the drive's 'Read offset' auto detected by CUERipper or had you set it manually?

The offset was detected automatically.

Remark: A freshly unpacked CUETools_2.2.2.zip with user_profiles_disabled was used.

**Comment by Barough** [comment]
Using a recently new 'setup' of CT 2.2.2 updated with the 'CUETools_2.2.2_2022-11-02_PR228' release with 'user_profiles_disabled'

**Comment by Barough** [comment]
The 'Read offset' on this drive in question was auto detected by CUERipper

```
Used drive  : ASUS SBW-06D2X-U   Adapter: 1  ID: 0
...
Read offset correction                      : 0
```

But EAC detected the 'Read offset'

**Comment by c72578** [comment]
> The 'Read offset' on this drive in question wasn't auto detected by CUERipper
> 
> ```
> Used drive  : ASUS SBW-06D2X-U   Adapter: 1  ID: 0
> ...
> Read offset correction                      : 0
> ```
> 
> But EAC detected the 'Read offset'. The offset for this drive is '106'

The `ASUS SBW-06D2X-U` is one of the few drives, where the offset has been purged from the AccurateRip's drive database [1]:

![ASUS_SBW-06D2X-U_Purged](https://user-images.githubusercontent.com/371551/203840463-1b88e2c6-bdc6-4b78-9cdf-045315d3362b.png)

In this case, the offset has to be entered manually in CUERipper.

[1] http://www.accuraterip.com/driveoffsets.htm

**Comment by Barough** [comment]
Never thought about looking on AR driveoffsets website.

Wonder why it have it have been purged........ maybe a email to Spoon can solve this 'mystery'.

**Comment by Barough** [comment]
A little side question....... is a new CUETools/Ripper release far away or?

**Comment by c72578** [comment]
> 
> Doesn't matter how many key disks i use with CUERipper.......

Just in case the offset is not detected automatically and has not been entered manually in CUERipper (at `offset 0`) or is unknown, it can also be found in the `.accurip` file after ripping a disc, e.g.:
`Offsetted by -103:`
Which means a `Read offset` of `103` for the drive.

**Comment by c72578** [comment]
> A little side question....... is a new CUETools/Ripper release far away or?

OT: The next release of CUETools will include the upcoming WavPack 5.6.0, which is currently in upstream preparation.
So - during the next weeks ...
