### ISSUE TITLE
[REQ] Please extend maximum INDEX timestamp.

### ISSUE THREAD

**Issue by SFtheGreat** [gchudov/cuetools.net#237]
Greetings.

Would it be possible to raise the current cap on the track INDEX timecode?
Currently it sits on ~140 minutes and I have been able to work on ~120 minute albums in the past, but recentely I stumbled upon a ~150 min one and CueTools is returning Invalid Stride error and refuses to process the files.
Link to discussion:
https://hydrogenaud.io/index.php/topic,118913.msg980695.html#msg980695

Perhaps a small modification in the sourcecode/cracking my copy of the software would do the trick?

**Comment by c72578** [comment]
@SFtheGreat Thanks for the report.
What are you using CUETools for, in case of this ~150 min album (e.g. verify, encode ...)?
Would it be possible for you to turn off `Verify using CTDB` just in this particular case, in order to process the files?
