### ISSUE TITLE
[2.1.7] .NET Exception: Value must be greater than or equal to minimum

### ISSUE THREAD

**Issue by Laserentchen** [gchudov/cuetools.net#24]
The following error occured in the test and in the copy stage of a secure rip when progress reached 100%. (Two suspicious sectors were found but rip verified OK (AR + CTDB) none the less.)
I could not reproduce the error with any disc.

Complete error message ([Fehlermeldung.txt](https://github.com/gchudov/cuetools.net/files/3613567/Fehlermeldung.txt)):

************** Ausnahmetext **************
System.ArgumentException: Value must be greater than or equal to minimum.  
&nbsp;&nbsp;bei ProgressODoom.AbstractProgressBar.set_Value(Int32 value)
&nbsp;&nbsp;bei CUERipper.frmCUERipper.<>c__DisplayClass27_0.<CDReadProgress>b__0()
&nbsp;&nbsp;bei System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
&nbsp;&nbsp;bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
&nbsp;&nbsp;bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
&nbsp;&nbsp;bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
&nbsp;&nbsp;bei System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
&nbsp;&nbsp;bei System.Windows.Forms.Control.InvokeMarshaledCallbacks()

**Comment by ha-korth** [comment]
also reported https://hydrogenaud.io/index.php/topic,115962.msg956972.html#msg956972

It appears this issue was addressed in [this commit](https://github.com/gchudov/cuetools.net/commit/9754a9a3282dd835e5544c618751c834e983fafc).

**Comment by Laserentchen** [comment]
Thanks a lot for your fast reply @ha-korth !
I will try this fix and create a new ticket if the error occurs again.
