### ISSUE TITLE
CUETools.ALACEnc.exe -s <wrong number> destroys audio

### ISSUE THREAD

**Issue by H2Swine** [gchudov/cuetools.net#241]
Try: 
`CUETools.ALACEnc.exe -s 7 wavefile.wav
`
The "7" is not an allowed value.
Expected: Either error message or -s 7 ignored
What happens: outputs a short file with all data invalid (according to ffmpeg, at least)

**Comment by c72578** [comment]
@H2Swine Thanks for your report.
A check of the specified `StereoMethod` will be added.

**Comment by c72578** [comment]
@H2Swine A fix has been prepared. Could you please check the build from here:
https://github.com/gchudov/cuetools.net/pull/243#issuecomment-1370190546

**Comment by c72578** [comment]
@H2Swine Thanks for testing and checking the other options.
Concerning `-m`: Yes, only `Estimate` is implemented:
https://github.com/gchudov/cuetools.net/blob/6def3a5664317444caae0725683067eff07e8617/CUETools.Codecs.ALAC/OrderMethod.cs#L5

The PR has been updated and the double full stop is not shown anymore at the end of error messages.
"was not found.." -> "was not found."
