### ISSUE TITLE
Crash if filename has special characters

### ISSUE THREAD

**Issue by manureini** [gchudov/cuetools.net#25]
Hello,

There is an issue if the artist or album contains a special character like ':' which should be removed
for a filename.

i.e. Path.GetInvalidFileNameChars();

https://github.com/gchudov/cuetools.net/blob/master/CUETools.Ripper.Console/Program.cs#L193

**Comment by c72578** [comment]
Remark: This affects only **`CUETools.Ripper.Console.exe`**
