### ISSUE TITLE
[CUETools 2.2.3] «Exception: Specified method is not supported.» on tta files

### ISSUE THREAD

**Issue by Mingun** [gchudov/cuetools.net#254]
Trying to convert a tta file to multiple tracks, I ran into this exception. Convert Settings:
![Convert Settings](https://user-images.githubusercontent.com/450131/216804068-07a69651-66d0-48c9-a452-1d4b4462beac.png)

**Comment by Mingun** [comment]
After change Decoder from **ffmpeg.dll** to **ttalib** on **Formats** tab in **Settings** error dissapears.
![изображение](https://user-images.githubusercontent.com/450131/216804351-235b53fb-2b4f-46f7-81f6-7db35dbbc934.png)

**Comment by c72578** [comment]
Just curious:
What was the reason, that you changed the CUETools 2.2.3 default `tta`-Decoder from `ttalib` to `ffmpeg.dll`?

**Comment by Mingun** [comment]
I do not changed nothing. Previously I used version 2.2.2, but it was crush with same error, as described in #207. So I updated to version 2.2.3, where instead of crashing and began to appear this error.

**Comment by c72578** [comment]
OK, this explains. Thanks for the info.

**Comment by c72578** [comment]
@Mingun Feel free to test a build, which allows decoding **`tta`** files using **`ffmpeg.dll`**:
https://github.com/gchudov/cuetools.net/pull/270#issuecomment-1494892578
