### ISSUE TITLE
[REQ] Monkey's Audio v10.xx

### ISSUE THREAD

**Issue by Barough** [gchudov/cuetools.net#261]
Please update Monkey's Audio v9.15
https://monkeysaudio.com/versionhistory.html

**Comment by c72578** [comment]
> Version 9.15 (February 15, 2023)
Changed: Made decoding around 10% faster by using a lookup table.

Sounds promising …

**Comment by Barough** [comment]
and then we have the optimizations that was made in 9.10

**Comment by Barough** [comment]
MA v10.07 Stable was released a couple of days ago.

**Comment by Neustradamus** [comment]
Version 10.09 (April 12, 2023)
- https://monkeysaudio.com/versionhistory.html

**Comment by Barough** [comment]
10.17 (June 29, 2023)
https://monkeysaudio.com/versionhistory.html

**Comment by Barough** [comment]
10.18 (August 10, 2023)
https://monkeysaudio.com/versionhistory.html
