### ISSUE TITLE
Add possibility to check one-track CD albums without cue

### ISSUE THREAD

**Issue by DarkVoyage** [gchudov/cuetools.net#262]
Currently you need to use at least dummy cue-sheet with one track to make CueTools understand that CD consists of only one track. Also you can't convert just one track. It writes: "Input file doesn't seem to contain a cue sheet or be part of an album..".

**Comment by c72578** [comment]
If you have only one track, without an embedded cue file, you can create an .m3u file, which contains only this single file.
Example attached:
[single_file_without_cue.zip](https://github.com/gchudov/cuetools.net/files/10791689/single_file_without_cue.zip)

**Comment by DarkVoyage** [comment]
Thanks, but that's not a solution. I'd better use dummy cue, because CueTools ignores the filename in cue and just takes any audio file it can find in directory. And personally I think of tracklists as garbage files. Don't keep and use them.

Would be nice, if CueTools was more flexible. But maybe this was made for some reason. Actually I knew G. Chudov at time he developed CueTools and it was already a problem at that time he didn't want to resolve.
