### ISSUE TITLE
.ape is unsupported

### ISSUE THREAD

**Issue by Gilgamesh0028** [gchudov/cuetools.net#263]
- fresh install of cuetools from latest stable release.
- using a .ape that plays in VLC
options:
![image](https://user-images.githubusercontent.com/98428877/220020537-d88d9f8c-b2ed-40a9-b282-b6852d5d020e.png)

no decoder or encoder offered for .ape, despite me having MAC_9.18 installed in the default location.
![image](https://user-images.githubusercontent.com/98428877/220020660-4e7fb5c4-834d-4acd-b738-e834a13224cd.png)

**Comment by c72578** [comment]
Please have a look at:
http://cue.tools/wiki/CUETools_Download#Installation

The dowloaded CUETools_2.2.3.zip file needs to be unblocked before unpacking.

**Comment by Gilgamesh0028** [comment]
It was already unblocked.

**Comment by c72578** [comment]
Which Antivirus-Software are you using?

**Comment by Gilgamesh0028** [comment]
None, save for the built in one on windows

**Comment by c72578** [comment]
It should look like this:

**Comment by c72578** [comment]
It should look like this:

![ape_decoders](https://user-images.githubusercontent.com/371551/220076188-2ce1fc7e-eec9-4ce8-a3f9-9508f25892f0.png)

So, normally there are two possibilities to decode .ape files.

`MAClib`, and also `ffmpeg.dll`

It seems that at least the following two files are blocked or missing on your system:

`CUETools_2.2.3\plugins\CUETools.Codecs.MACLib.dll`
`CUETools_2.2.3\plugins\CUETools.Codecs.ffmpegdll.dll`

**Comment by c72578** [comment]
@Gilgamesh0028 Could you find out in the meantime, what made the ape Decoders disappear on your system?

**Comment by Gilgamesh0028** [comment]
Currently away from home, but I'll check the logs as soon as I get back.

**Comment by c72578** [comment]
@Gilgamesh0028 Could you please try a different (newer) build of CUETools and see if the .ape Decoders show up?
E.g. `CUETools_2.2.3_2023-02-11_git_4d06471_Add_GUI_setting_for_CreateCUEFileInTracksMode.zip` from: 
https://github.com/gchudov/cuetools.net/pull/258#issuecomment-1426706384

Please `unblock` the downloaded zip file (after checking its integrity) before unpacking it.

**Comment by c72578** [comment]
However, `.ape` is supported by CUETools. Closing this issue.
