### ISSUE TITLE
Repair and correct offset at once

### ISSUE THREAD

**Issue by DarkVoyage** [gchudov/cuetools.net#265]
There's no such encode option yet, but if you try to add offset during repair, you will get the offset doubled and file would not be repaired properly. This is not needed too often of course, but maybe it is not such a big deal to combine two encoding modes.

**Comment by DarkVoyage** [comment]
I mean that this is not bug, but a feature request. And of course you can disable manual offset setting for "offset fix", "repair" and "repair and fix offset" options.

**Comment by DarkVoyage** [comment]
There's two different variants to resolve:
- disable manual offset for repair and offset fix modes;
- fix how manual offset works during repair.

Maybe you want to leave that decision for user, if he wants to set any offset he likes during repair. So yes - setting offset during repair makes wrong offset and doesn't repair the rip. It is a bug.

**Comment by c72578** [comment]
In case of `fix offset`, the `WriteOffset` is already set to `0` while running the script:
https://github.com/gchudov/cuetools.net/blob/5aec3fb5d32de13e0ee679d97305732e0261f681/CUETools.Processor/CUESheet.cs#L4524

@DarkVoyage Could you please give the build from here a try using the `repair` script:
https://github.com/gchudov/cuetools.net/pull/287#issuecomment-1625971891

**Comment by c72578** [comment]
@DarkVoyage @ha-korth
A new fix has been prepared, which avoids applying the offset twice: #288 
This way it is also possible to correct the offset and repair a rip in one go.
