### ISSUE TITLE
Mode294 does not work on GH22LS51

### ISSUE THREAD

**Issue by anemochore** [gchudov/cuetools.net#283]
I have used EAC well for 12 years or more. But recently when ripping a brand-new CD, it gave me errors on two tracks, so I've decided to use a 'modern' alternative CUERipper. And... it was frustrating. 'Auto' mode (I don't know exact menu name since it's not documented on the ages-old [manual](http://cue.tools/wiki/CUERipper_Settings)) gave 31 retries per 1 percent. So I googled and figured that 'Auto' means C2 error feature so I've changed it Mode294 and the result was the same, so again Mode296 then the result was fine (which means ripping could be finished. Not without errors). 

![화면 캡처 2023-06-11 115213](https://github.com/gchudov/cuetools.net/assets/8731054/eb7dff78-3002-4682-a0fd-7e3183cd0eab)

I don't know why it falsely detect C2 features. Is it not possible to get info from some DB? I saw on [another issue](https://github.com/gchudov/cuetools.net/issues/107) that hardware info is somewaht hard-coded, which seems really not 'modern.' 

And about the number of retry, if it is identical to the 're-reads' of EAC, I think the default value is unnecessarily too big since there'is no way to adjust manually. Please check the 'Error recovery quality' section on [EAC options recommendation](https://wiki.hydrogenaud.io/index.php?title=EAC_Options).

**Comment by c72578** [comment]
@anemochore Thanks for your report, that the detected C2 Error `Mode294` is not working on GH22LS51 and the info that `Mode296` is OK.
> So I googled and figured that 'Auto' means C2 error feature 

This is what the tooltip says:

![CUERipper_C2_Error_Mode_Tooltip_crop](https://github.com/gchudov/cuetools.net/assets/371551/7104298a-4cd6-491e-9900-8f3ff5b2e86c)
