### ISSUE TITLE
Latest MusicBrainz metadata not fetched by CTDB

### ISSUE THREAD

**Issue by eprillios** [gchudov/cuetools.net#293]
Thanks for this amazing set of software! I have started ripping CDs again using CUERipper, and it works splendidly and hassle-free.

I've come to notice that my latest additions (e.g. for when a disc was previously unknown) to the MusicBrainz database are not reflected in the metadata fetched by CUERipper from CTDB. Waiting for a week has not changed this issue.

I've read that a schema change on the end of MusicBrainz could be the culprit. [This topic on Hydrogenaudio](https://hydrogenaud.io/index.php/topic,124593/) describes problems similar to what I am experiencing.

Please let me know if I can be of any help providing further details.

**Comment by c72578** [comment]
The `db.cue.tools` issue has been fixed in the meantime:
https://github.com/gchudov/db.cue.tools/issues/21#issuecomment-1729501906
