### ISSUE TITLE
Error when ripping CD with LG Drive [HL-DT-ST DVDRAM GP65NB60 RF01].  "Exception: Error reading CD: medium error: UNRECOVERED READ ERROR

### ISSUE THREAD

**Issue by bbcoursera** [gchudov/cuetools.net#294]
This doesn't happen on every CD, but when I googled the error, it seems this hit previous versions of LG drives, and there was a fix for those drives.  I could be wrong, but if I understand the fix, this drive may need to added to the list of drives that trigger it.

I believe it is happening on the 2nd or 3rd track, but I can't be sure because the progress bar does not indicate what track it is currently working on.  

Also, there does not seem to be a log saved to the destination folder when the rip fails, so I am not sure how to provide more info.

**Comment by c72578** [comment]
It looks like this issue is related to the condition of the CDs (scratches etc.) in combination with the drives. Sometimes a CD can still be read on a different drive. Cleaning/polishing of the affected CDs could help (instructions can be found in the internet).
