### ISSUE TITLE
Object reference not set to an instance of an object..

### ISSUE THREAD

**Issue by aphex3k** [gchudov/cuetools.net#296]
CUETools 2.2.4 fails on Windows 11 22H2 after selecting the source drive and pressing the go button.

![image](https://github.com/gchudov/cuetools.net/assets/433270/f9b8d649-cfae-445a-8207-d5997ddfedf0)
![image](https://github.com/gchudov/cuetools.net/assets/433270/19f8c0a5-2d9e-4d0a-966e-2fca386bcb30)

**Comment by aphex3k** [comment]
I was recommended using CUETools as a EAC user because it has issues to. In CUERipper I get this error instead: 

![image](https://github.com/gchudov/cuetools.net/assets/433270/eb0947b0-7bce-4190-999b-80cb992d3012)

**Comment by aphex3k** [comment]
When I select `Auto` or `Mode294`, it fails with the same error as above. When I select `None` or `Mode296`, I end up with a correctly ripped CD.

**Comment by aphex3k** [comment]
While the original issue is not resolved, I'm fine with closing this issue as CUERipper seems to do the trick...

**Comment by c72578** [comment]
@aphex3k Thanks for your report.
Note from screenshot: The affected drive concerning C2 Error Mode is a `MATSHITA DVD-R UJ-868 KB19`.
