### ISSUE TITLE
Add support for AIFF

### ISSUE THREAD

**Issue by DarkVoyage** [gchudov/cuetools.net#298]
Should be no problem to add at least as input format with ffmpeg. It is common for Apple users, who download and share aiff from Bandcamp and rip CDs too.

**Comment by DarkVoyage** [comment]
Thanks for info. It is usable for external formats. But it would be better, if you just add internal support with ffmpeg.dll, because this is one of basic formats that should be supported.

**Comment by c72578** [comment]
@DarkVoyage Could you please test the build provided here:
https://github.com/gchudov/cuetools.net/pull/299

**Comment by DarkVoyage** [comment]
It doesn't work. It gives following message and then CueTools crashes after any action.
X:\......aiff: Specified method is not supported..

By the way, TAK can be decoded by ffmpeg, may remove the need for takc.exe for those, who don't need to encode.

**Comment by c72578** [comment]
@DarkVoyage Did you copy the required ffmpeg 6.0 dlls to plugins\x64 ?

**Comment by DarkVoyage** [comment]
Ok. It works. Thanks.
