### ISSUE TITLE
Add releases to github releases page

### ISSUE THREAD

**Issue by JuniorJPDJ** [gchudov/cuetools.net#30]
Could you please add (at least latest version) to GitHub Releases page?

**Comment by c72578** [comment]
Thanks for your report.
The latest released version 2.1.7 has been added:
https://github.com/gchudov/cuetools.net/releases

**Comment by c72578** [comment]
Additionally, CUETools 2.1.6 has been tagged and added to the Releases:
https://github.com/gchudov/cuetools.net/releases/tag/v2.1.6
