### ISSUE TITLE
[2.2.4] FLAC decoding issue with ffmpeg plugin

### ISSUE THREAD

**Issue by ha-korth** [gchudov/cuetools.net#300]
CUETools 2.2.4 hangs/freezes at 'Analyzing input file'.
Using ffmpeg 6.0 dll files from https://github.com/GyanD/codexffmpeg/releases/download/6.0/ffmpeg-6.0-full_build-shared.zip
libFLAC and libFLAKE (cuetools) decoders work fine.

CUETools 2.2.3 with ffmpeg 4.3 plugin works okay.

**Comment by c72578** [comment]
Tests of previous versions of [FFmpeg.Autogen](https://www.nuget.org/packages/FFmpeg.AutoGen) using the corresponding ffmpeg dlls have shown, that the issue has appeared from ffmpeg `4.4` to `5.0`:

`FFmpeg.AutoGen 4.4.1.1:` OK
`FFmpeg.AutoGen 5.0.0:` Analyzing input file...
