### ISSUE TITLE
[QUESTION] Time for a new release or?

### ISSUE THREAD

**Issue by Barough** [gchudov/cuetools.net#309]
Wondering if it's time for a new release. Been a 'few' updates since the previous time.
Tested the latest test release (MAC_SDK 10.37) and it's works fine.

**Comment by c72578** [comment]
Yes, CUETools 2.2.5 is currently in preparation.
Thanks for testing #308

**Comment by c72578** [comment]
[CUETools 2.2.5](https://github.com/gchudov/cuetools.net/releases/tag/v2.2.5) has been released.
