### ISSUE TITLE
CUERipper: failed to load ripper module

### ISSUE THREAD

**Issue by somehowwentverywrong1** [gchudov/cuetools.net#32]
<img src=https://i.imgur.com/XZXv2wx.png>
Don't really know why this is happening. What am I doing wrong?

**Comment by c72578** [comment]
This typically happens, when the following is missing:
**`plugins\CUETools.Ripper.SCSI.dll`**

Please check, that all files from **`CUETools_2.1.7.zip`** have been unpacked correctly and that the subfolder **`plugins`** is present inside the CUETools_2.1.7 directory.

**Comment by somehowwentverywrong1** [comment]
> 
> 
> This typically happens, when the following is missing:
> **`plugins\CUETools.Ripper.SCSI.dll`**
> 
> Please check, that all files from **`CUETools_2.1.7.zip`** have been unpacked correctly and that the subfolder **`plugins`** is present inside the CUETools_2.1.7 directory.

It's there, 26KB.

**Comment by c72578** [comment]
Are these files present?
**`plugins\Bwg.Scsi.dll`**
**`plugins\Bwg.Logging.dll`**
**`plugins\Bwg.Hardware.dll`**

**Comment by somehowwentverywrong1** [comment]
> 
> 
> Are these files present?
> **`plugins\Bwg.Scsi.dll`**
> **`plugins\Bwg.Logging.dll`**
> **`plugins\Bwg.Hardware.dll`**

Yes.

**Comment by ha-korth** [comment]
Check the Properties of CUETools_2.1.7.zip to see if Windows may have put a Block on the archive.
[Known Issues When Unpacking the Archive](http://cue.tools/wiki/CUETools_Download#Known_Issues_When_Unpacking_the_Archive)

**Comment by c72578** [comment]
This typically happens, when unpacking the CUETools_2.1.7.zip file using the Windows unzip functionality (e.g. Extract All...). Either you unblock the relevant files as mentioned by @ha-korth  (first candidate: plugins\CUETools.Ripper.SCSI.dll) or you can use an alternative program for unpacking, e.g. 7-zip ...

**Comment by somehowwentverywrong1** [comment]
> 
> 
> Check the Properties of CUETools_2.1.7.zip to see if Windows may have put a Block on the archive that would prevent CUERipper from accessing `plugins\`
> [Known Issues When Unpacking the Archive](http://cue.tools/wiki/CUETools_Download#Known_Issues_When_Unpacking_the_Archive)
> https://hydrogenaud.io/index.php?msg=959968

Thank you!
