### ISSUE TITLE
CUERipper: failed to load ripper module

### ISSUE THREAD

**Issue by KRadiants** [gchudov/cuetools.net#337]
Hello :)

I stumbled upon [this answer](https://github.com/gchudov/cuetools.net/issues/32#issuecomment-579471772) from a thread from 2020. The user asks if these files are present. OP said yes, but i'm missing plugins\Bwg.Scsi.dll

Where can I find a download link for this file ?

**Comment by c72578** [comment]
The file `plugins\Bwg.Scsi.dll` is part of the CUETools release zip files.
E.g. in: https://github.com/gchudov/cuetools.net/releases/download/v2.2.5/CUETools_2.2.5.zip

**Comment by c72578** [comment]
PS: **Unblock** the downloaded CUETools_2.2.5.zip file first, before unpacking.
See: http://cue.tools/wiki/CUETools_Download#Known_Issues_When_Unpacking_the_Archive

**Comment by KRadiants** [comment]
Ok so turns out i do have the dll, but I don't need to unblock the archive
