### ISSUE TITLE
CUERipper: "Preserve HTOA" setting not working since 2.2.6

### ISSUE THREAD

**Issue by kprueckl** [gchudov/cuetools.net#341]
I just coincidently noticed that since update to CUERipper 2.2.6 no more HTOA files are created during the ripping process. The setting "Preserve HTOA" has no impact and the behavior is also not changing when the setting is flipped to false and true again.
My drive is a "HL-DT-ST BD-RE BH16NS55 1.05".
I've double checked, in CUERipper 2.2.5 it is working and HTOA files are created.

**Comment by kprueckl** [comment]
OK, I think I have an answer: is related to this change: [c72578](https://github.com/gchudov/cuetools.net/commits?author=c72578)
though, I was not able find the related UI setting which might be because the commit description only mentiones CUETools, but not CUERipper.
Anyhow, I've edited settings.txt manually for the moment

**Comment by drallim33** [comment]
This should be considered a bug, if I select preserve HTOA and it does not, that's a bug.

Preserving all HTOA should be the default, discarding HTOA shorter than five seconds should be an additional option.

The main purpose of preserving HTOA is to be able to keep a full disc image while having per-track files. It's a compromise for people who don't want single file rips where tagging is limited. 

2.2.6 breaks this functionality and this change should be reverted, people will be unknowingly making imperfect rips.
