### ISSUE TITLE
CUETools doesn't support CUETools.FLACCL.cmd.exe compression modes

### ISSUE THREAD

**Issue by acmodeu** [gchudov/cuetools.net#342]
When I set flac encoder to use CUETools.FLACCL.cmd.exe with multiple comression setting according:

![cuda](https://github.com/user-attachments/assets/66b5fd42-4802-46ef-8e4f-348a4d506480)

and try to compress, I get the following error:

![error](https://github.com/user-attachments/assets/fbf00c27-9a15-4322-afc9-4da4f001b814)

Encoding with `-%M` removed work perfectly.

Encoding using CUETools.FLACCL.cmd.exe in console with compression set also works.

**Comment by c72578** [comment]
@acmodeu Please select a compression level once in CUETools using the slider, then it is supposed to work.

**Comment by c72578** [comment]
Notes concerning this issue:

The `settings.txt` file show what is going on:
- Command line encoder freshly added:
```
=    {
=      "$type": "CUETools.Codecs.CommandLine.EncoderSettings, CUETools.Codecs",
=      "Name": "cuda",
=      "Extension": "flac",
=      "Lossless": true,
=      "SupportedModes": "0 1 2 3 4 5 6 7 8",
=      "Path": "CUETools.FLACCL.cmd.exe",
=      "Parameters": "-%M -o %O -"
=    }
```
- Command line encoder added and compression level selected:
```
=    {
=      "$type": "CUETools.Codecs.CommandLine.EncoderSettings, CUETools.Codecs",
=      "Name": "cuda",
=      "Extension": "flac",
=      "Lossless": true,
=      "SupportedModes": "0 1 2 3 4 5 6 7 8",
=      "EncoderMode": "8",
=      "Path": "CUETools.FLACCL.cmd.exe",
=      "Parameters": "-%M -o %O -"
=    }
```

- Difference:
**`=      "EncoderMode": "8",`**

So, the `EncoderMode` is missing after freshly adding the Encoder and has to be set.

**Comment by acmodeu** [comment]
@ha-korth my encoder settings window is very different from yours.

@c72578 thank you! Setting initial compression fixed the issue.
