### ISSUE TITLE
Generated CUE file comment

### ISSUE THREAD

**Issue by acmodeu** [gchudov/cuetools.net#343]
Can auto comment "REM COMMENT "CUETools generated dummy CUE sheet"" be disabled somehow?

**Comment by c72578** [comment]
@acmodeu Would you like to have a different `COMMENT` like:
`REM COMMENT "CUETools generated dummy CUE sheet"`
->
`REM COMMENT "Different comment"`

or remove the `REM COMMENT` line completely?

**Comment by acmodeu** [comment]
Yes, I would like an option to not add it.
