### ISSUE TITLE
CUERipper 2.2.6 fails with IOctlFailed

### ISSUE THREAD

**Issue by mpe85** [gchudov/cuetools.net#349]
My drive is a Pioneer BD-RW BDR-UD04 1.14 inside a Verbatim model 43888.

When ripping a disc with CUERipper 2.2.6 it fails with an IoctlFailed exception. It does not matter which CD I use.
I found other (already resolved) issues with similar problems (like https://github.com/gchudov/cuetools.net/issues/164) which indicate that it may a problem with USB 3.
When I connect my drive to a USB 2 port it seems to work.

**Comment by mpe85** [comment]
When I set the C2 Error Mode explicitly to Mode296 (instead of Auto) it works perfectly.

The exact drive name is `PIONEER BD-RW   BDR-UD04 USB Device`.

**Comment by c72578** [comment]
Thanks for the report and the additional info concerning C2 Error Mode.
