### ISSUE TITLE
[2.1.7] CUERipper - duplicate FLAGS subcode command per track in CUE sheet

### ISSUE THREAD

**Issue by ha-korth** [gchudov/cuetools.net#41]
This has been on the [Known issues](http://cue.tools/wiki/CUERipper#Known_issues) list for a while.

[When detected] A duplicate FLAGS subcode command is added per track to the CUE when 'Test & Copy' is enabled or if you try to re-rip the CD without cycling the tray (eject/load). 
Only one FLAGS command is allowed per track per the original Golden Hawk specification.

[samples.zip](https://github.com/gchudov/cuetools.net/files/4326485/samples.zip)

**Comment by c72578** [comment]
Thanks for this bug report.
The reason for currently appearing duplicate or multiple lines containing `FLAGS` can be found here:
https://github.com/gchudov/cuetools.net/blob/18f00da89db91d3e90af53467a35872757cb7544/CUETools.Processor/CUESheet.cs#L3764

Every time, when the method `DetectGaps()` is called, an additional line containing the `FLAGS` of a track is added to the cuesheet. In case of `Test & Copy` this is two times, and as you describe, when a CD is ripped multiples times without eject/load in between, multiple lines containing the `FLAGS` are added.

**Comment by c72578** [comment]
@ha-korth, attached you will find a current build from PR #42 for testing.

[CUETools_2.1.7_20200315git4ea069f.zip](https://github.com/gchudov/cuetools.net/files/4333915/CUETools_2.1.7_20200315git4ea069f.zip)

**Comment by ha-korth** [comment]
All CUE files are identical (no duplicate lines) after several test runs.

**Comment by c72578** [comment]
Thanks for testing
