### ISSUE TITLE
.net Standard

### ISSUE THREAD

**Issue by pkoelbl** [gchudov/cuetools.net#5]
I found a super old version of your code posted to some forum on the web. I ported over it to use in .net standard so i could use Xamarin to encode audio to FLAC. I posted it up on nuget here: https://www.nuget.org/packages/CUETools.Codecs.FLAKE
If you want me to take it down i can pull it down no problem. Didn't realize it was still an active project until i stumbled upon this.

**Comment by c72578** [comment]
No problem, feel free to use it according to the license of **`CUETools.Codecs.FLAKE`**
```
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
```
