### ISSUE TITLE
Hangeul in CUERipper problems

### ISSUE THREAD

**Issue by ChaseYUL99** [gchudov/cuetools.net#58]
After ripping a K-pop album (including hangeul alphabet), all hangeul text in files name and details are replaced by underscores.

**Comment by ha-korth** [comment]
With CUERipper closed, try changing `FilenamesANSISafe=1` to `FilenamesANSISafe=0` in the settings file and save.
If running normally, the settings file location is `%appdata%\CUERipper\settings.txt`
If running as portable, the settings file location is a subfolder `\CUERipper\settings.txt`

**Comment by ChaseYUL99** [comment]
It works, thank you very much.
