### ISSUE TITLE
Too Many Images Prevents Image Picker from Opening

### ISSUE THREAD

**Issue by JediSQL** [gchudov/cuetools.net#6]
During Convert, if there are too many JPEG image files in the folder with the CUE file, and its sub-folders, the "Select the best match "dialog box (to pick the album art image" does not open, and CUETools jumps straight to the "Select the best match "dialog box that picks the meta data source. It seems 31 image files is OK; 32 is too many.
I'm running CUETools 2.1.6 on Windows 10 (1803).

**Comment by c72578** [comment]
Thanks for your report.
The maximum of 32 for `maxChoice` is currently defined here:
https://github.com/gchudov/cuetools.net/blob/33f922e68f209303e221a21a7a2f2b0eaee8b4e6/CUETools.Processor/CUESheet.cs#L3017

The following line later on in the code is responsible for not showing the list of found images, when there are more than 32:
https://github.com/gchudov/cuetools.net/blob/33f922e68f209303e221a21a7a2f2b0eaee8b4e6/CUETools.Processor/CUESheet.cs#L3040

Which behavior do you expect or how many images should be the maximum in your case?

**Comment by JediSQL** [comment]
"How many?" is hard question to answer. I don't have the time to analyze the code for any performance impacts that might result from too large a number. Someone more familiar with the code should make that decision. Does there actually need to be a limit? Was that a decision made back when 1024x768 was the standard screen size and $500 computers didn't have quad-core, 3 GHz processors and terabyte storage?

I have, so far, 288 WAV/CUE/JPG file sets in the folder structure below. As time goes on, I have to keep splitting folders so that I can do encodings with CueTools. In my experience as a programmer, I have found that whenever software sets a limit, there is someone that exceeds it. Whatever the limit is, if it is exceeded, there should be some messaging to the user about what happened and how to work around it. Silent, mystery behavior is aggravating, and it makes folks walk away.

As long as the list of image names is alphabetized, I'd think that 128 or 256 image names would be manageable. But even at 256, if I had all my files in one folder, I still would have run into the problem, and it would probably have been harder to figure out.

RipCUE
+-A
+-B
+-C
+-DEF
+-GHI
+-JK
+-L
+-M
+-NOPQ
+-RS
+-TUVWXYZ
+-Various
+-Zappa
  +-Zappa, Frank 1
  +-Zappa, Frank 2
  +-Zappa, Frank 3
  +-Zappa, Frank 4
  +-Zappa, Frank Singles
  +-Zappa, Frank YCDTOSA
  +-Zappa-Beat the Boots
  +-Zappa-Beefheart
  +-Zappa-Mothers

Thank you for taking the time to look into this. I appreciate it, at least from the point of knowing that it's not me :-) !
Sincerely,
Dan

**Comment by c72578** [comment]
Dear Dan,
thanks for the feedback.
I did some tests in the meantime with 9999 jpg files in the folder and subfolders of a cue sheet.

The following info shows the memory consumption from Windows task manager and the time it took to analyze:
<pre>
16.4 MB CUETools started
  Go
  Analyzing input file... (1 min 2 s)
  461.1 MB Select best match (online album)
  463.0 MB Select best match (album art)

CPU:  i7-3687U, nothing special
Path length of each image file: 113 characters
</pre>
Remark: the current limit of 32 was rather coming from a typical situation of having just one ore a few images inside an album folder.
So I guess, I will increase the `maxChoice` limit. What I see from your message above is, that `512` would be sufficient for your number of images. And if there are lots of images (thousands) in the folder of the cue sheet and its subfolders: display an info message and still allow to choose an image.

Best regards
Wolfgang

**Comment by JediSQL** [comment]
Cool, thanks. I'll keep an eye out for the new release!
