### ISSUE TITLE
Exception: Error reading CD

### ISSUE THREAD

**Issue by zordaz** [gchudov/cuetools.net#64]
On my new Windows 10 laptop both CUERipper 2.1.6 and 2.1.7 gives an error (see image) when ripping CD's. It seems that after starting the laptop CUERipper is able to rip one CD, but when you want to rip a second one, the error occurs.
Exact Audio Copy works fine on the same laptop. The setup also worked fine with CUERipper 2.1.6 on my old Win10 laptop.

I am using a external USB Samsung SE-208 CD/DVD-drive which works fine on other computers. 

<img width="338" alt="Knipsel" src="https://user-images.githubusercontent.com/16536495/96237868-16ff1f80-0f9e-11eb-97a8-3b9d39b4ad74.PNG">

**Comment by c72578** [comment]
@zordaz Thanks for your report.
What happens, if you close CUERipper on the affected Windows 10 laptop after ripping one CD and start it again for the next CD?

> I am using a external USB Samsung SE-208 CD/DVD-drive which works fine on other computers.

Does this mean, when you connect this USB Samsung SE-208 CD/DVD-drive to a different computer, then CUERipper works properly and you can rip more than one CD without any error?

Thanks

**Comment by zordaz** [comment]
> 
> 
> @zordaz Thanks for your report.
> What happens, if you close CUERipper on the affected Windows 10 laptop after ripping one CD and start it again for the next CD?
> 
> > I am using a external USB Samsung SE-208 CD/DVD-drive which works fine on other computers.
> 
> Does this mean, when you connect this USB Samsung SE-208 CD/DVD-drive to a different computer, then CUERipper works properly and you can rip more than one CD without any error?
> 
> Thanks
I have to test it again with you suggestion, but I am not able to test on different computer, because I only have one MS Windows laptop, the rest is Linux (and CUERipper never worked properly via Wine).

What I also meant is that the CD/DVD-drive works is working fine in general; I am able to play, rip discs with other software on the affected and on other computers, including Linux.

**Comment by c72578** [comment]
> I am using a external USB Samsung SE-208 CD/DVD-drive which works fine on other computers.

@zordaz Could you please post details concerning the drive model and the firmware version?
There are e.g. SE-208AB and SE-208DB models around (https://www.firmwarehq.com/Samsung/drives.html).

I recently purchased a SAMSUNG Slim Portable Writer Model SE-208 for testing, which turned out to be a SE-208DB/TSBS with original firmware TS01. The reported issue "Exception: Error reading CD" could not be reproduced with this drive. Multiple different CDs could be ripped one after the other without any error. Newer firmware versions TS02 and TS03 for the SE-208DB are also working properly
CUERipper reports my drive like this:

![CUERipper_SE-208DB_TS01](https://user-images.githubusercontent.com/371551/107859682-6285e500-6e3b-11eb-86b1-937bbf1ebcb6.png)

**Comment by c72578** [comment]
@zordaz The detailed drive model is probably also printed at the bottom of your drive. Could you please post the details here, which drive you have got? According to the DAE Drive features database, there are several models of SE-208 around:
```
SE-208AB
SE-208BW
SE-208DB
SE-208DB
SE-208FB
SE-208GB
```
Thanks and best regards
Wolfgang

[1] https://www.daefeatures.co.uk/search?manufacturer=0&model=SE-208&accurate_stream=All&caching=All&c2=All&htoa=All&overread=All

**Comment by zordaz** [comment]
It's a SE-208DB/TSBS with F/W TS01.
I have some CD's to rip, will test it again.
Is it possible that this issue is related to https://github.com/gchudov/cuetools.net/issues/71 ?

**Comment by c72578** [comment]
@zordaz Thanks for checking. So, it is the same drive model, which I have got here for testing (no issue so far).
The situation is different compared to #71, because the SE-208DB/TSBS drive is a USB 2.0 drive.
Looking forward to your next ripping results.

**Comment by c72578** [comment]
OK, thanks for the good news.
