### ISSUE TITLE
[CUETools] CUE sheet Error when TAB used for indentation.

### ISSUE THREAD

**Issue by ha-korth** [gchudov/cuetools.net#65]
CUETools throws an error (e.g. Exception: Indexes must be in chronological order) when a TAB is used for indentation within a CUE sheet.

The original Golden Hawk CDRWIN [User's Guide](https://web.archive.org/web/20070221154246/http://www.goldenhawk.com/download/cdrwin.pdf) (Appendix A) didn't specify what type of indentation should be used.

> Formatting syntax:
> Indentation and spacing between command lines does not interfere
> with CDRWIN compiling a cuesheet. Cuesheet commands are not
> case sensitive. However, when editing a cuesheet, it is good
> programming practice to use indentation and spacing to keep your
> cuesheet orderly.

CUETools should be able to detect the TAB character when parsing a CUE sheet and handle as whitespace (or throw a better error message).

See https://hydrogenaud.io/index.php?topic=120100 for a recent example.

**Comment by c72578** [comment]
When finding the start of a `CUELine`, the program currently searches only for spaces.
https://github.com/gchudov/cuetools.net/blob/6fcd5b92d79e4db2c8e47fcfe7a410145f033a68/CUETools.Processor/CUELine.cs#L31
Tabs need to be considered there too, in addition to spaces, e.g.:
```C#
while ((start < lineLen) && ((line[start] == ' ') || (line[start] == '\t')))
```
