### ISSUE TITLE
CUETools will not run on Windows 7 Pro 64 bit Dell Latitude Laptop

### ISSUE THREAD

**Issue by GVCCbob** [gchudov/cuetools.net#7]
https://www.solvusoft.com/en/files/error-virus-removal/exe/windows/windows-software-developer/third-party-application/cuetools-exe/

My Laptop is perfect, all stuff installed.

Unzip File for Downloads, creates CueTools.exe folder in downloads, select either:

Just unpack the archive to any folder; no setup required. CUETools.exe and CUERipper.exe are the main applications to run.

App tries to launch and then message app will not run!

https://hydrogenaud.io/index.php/topic,117107.0/topicseen.html

**Comment by vlakoff** [comment]
Quoting the thread on hydrogenaudio:

>I figured out how to extract from the download folder to the desktop, all file in the folder. 
>
>Eureka, the application launched.

This issue can be closed…
