### ISSUE TITLE
[CUETools & CUERipper 2.1.8] FLACCL not found

### ISSUE THREAD

**Issue by ha-korth** [gchudov/cuetools.net#82]
<img width="273" alt="CUETools_218_FLACCL" src="https://user-images.githubusercontent.com/36651918/108653942-b1fc8e80-7495-11eb-8d9a-2e69d8ab88d3.png">
CUETools & CUERipper 2.1.8

I went back to a test build from 03-15-2020 https://github.com/gchudov/cuetools.net/pull/42
and get the same error.

A test build from 01-14-2020 https://github.com/gchudov/cuetools.net/commit/2bde92380a2ed7cf46e67609b345e2be9d211639 
does not have the error.

**Comment by c72578** [comment]
@ha-korth Thanks for this report.
The constructors need to be updated for FLACCL too. Similar as it was done for ALAC in 18c6c1ae3af6884297599f8c2d1016f33b8d2b44

Affected lines in **`FLACCLWriter.cs`**:
https://github.com/gchudov/cuetools.net/blob/b108b7f90f50bbd176eb8b806535bf5914e1c585/CUETools.Codecs.FLACCL/FLACCLWriter.cs#L375

https://github.com/gchudov/cuetools.net/blob/b108b7f90f50bbd176eb8b806535bf5914e1c585/CUETools.Codecs.FLACCL/FLACCLWriter.cs#L399

I will prepare a fix.

**Comment by c72578** [comment]
A fresh CI build from #84 has been prepared for testing:
[CUETools_2.1.8_2021-02-22_git_52faf46.zip](https://github.com/gchudov/cuetools.net/files/6025139/CUETools_2.1.8_2021-02-22_git_52faf46.zip)

**Comment by Barough** [comment]
> 
> 
> A fresh CI build from #84 has been prepared for testing:
> [CUETools_2.1.8_2021-02-22_git_52faf46.zip](https://github.com/gchudov/cuetools.net/files/6025139/CUETools_2.1.8_2021-02-22_git_52faf46.zip)
> **`SHA256: 08cc52401d41eb08f5906fe522c295f5fc0aa563b93b10b2e12faac9817b69d1`**

Tested/Working :)

**Comment by ha-korth** [comment]
After a quick test it seems okay now.
