### ISSUE TITLE
[CUETools 2.1.8] Custom added FLAC EXE encoder fails

### ISSUE THREAD

**Issue by Barough** [gchudov/cuetools.net#83]
Custom added FLAC EXE encoder fails
https://i.imgur.com/B7zW0kO.png

FLAC Parameter used : -8 -V - -o %O %P

No issue with v2.1.6 or v2.1.7

**Comment by ha-korth** [comment]
Shouldn't that be `-8 -V - -o %O -P %P` ?

**Comment by Barough** [comment]
Your so right korth. My fault. Forgot the -P.  :D
