### ISSUE TITLE
[CUETools DB] Unable to browse past the first results

### ISSUE THREAD

**Issue by YhenZN** [gchudov/cuetools.net#89]
In the past when visiting http://db.cue.tools, it used to be possible to use the arrows at the bottom of the page to browse other results, but nowadays the arrows are greyed out and you're stuck with the first 10 results which makes it impossible for me to find the albums I'm looking for.
Is it possible to restore the previous behaviour or is there a way to search for certain albums?

**Comment by ha-korth** [comment]
Wrong project. I think you're looking for https://github.com/gchudov/db.cue.tools
