### ISSUE TITLE
[REQUEST] Codec Updates

### ISSUE THREAD

**Issue by Barough** [gchudov/cuetools.net#90]
HI

Please update these codecs for CUETools/CUERipper

WavPack to v5.4.0 (OK)
Monkeys Audio to v7.xx
FLAC/libFLAC to v1.3.3 (OK)

[EDIT]
While your making the updates so would it be nice if you could upd ate these 2 also :
L.A.M.E. (libmp3lame.dll to v3.100.1 (Rarewares) )  (OK)
UnRAR (to v6.1.x (https://www.rarlab.com/rar/UnRARDLL.exe) )  (OK)

**Comment by c72578** [comment]
@Barough thanks for your request.
**`libFLAC`** will be updated first. See https://hydrogenaud.io/index.php?topic=120750.0 for further details.

**Comment by Barough** [comment]
Have manually updated libFLAC_dynamic.dll to v1.3.3.git-ce6dd6b5 & Unrar.dll to v6.1.x already. Did that a couple of days after the HF1 release. ;)

**Comment by c72578** [comment]
@Barough A PR for updating WavPack to 5.4.0 has been prepared.
Please find a current build for testing here: https://github.com/gchudov/cuetools.net/pull/102

**Comment by Barough** [comment]
@c72578 Have made a few tests and it works fine.
The only thing i've noticed is that when you check the properties of a song in foobar2000 so does it report
<WAVPACK_VERSION> : 5
Not sure if its gonna be like that or not.

**Comment by c72578** [comment]
@Barough Thanks for testing.
`<WAVPACK_VERSION> : 5` is fine. This is the same, what `wvunpack` reports.
```
wvunpack.exe -s foo.wv
encoder version:   5
```
WavPack5FileFormat:
http://www.wavpack.com/WavPack5FileFormat.pdf

**Comment by Barough** [comment]
Ok :)

**Comment by Barough** [comment]
Any progress being made on the Monkeys Audio codec?

**Comment by Barough** [comment]
Monkeys Audio is up to v7.x now
